### ISSUE TITLE
New pointer to the 10x example

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/dcp#107]
In order to test 10X data bundles the metadata repo now has a 10X example that will now be supported. In order to link this sheet to other DCP integration tests we need to add a new pointer in the DCP repo could we add 

1. some representative 10x files from a preview dataset to an s3 bucket (contact Mallory or Matt for examples)
2. a pointer to the data
3. a pointer to the sheet in dcp/tests/fixtures/datasets

The pointer should be:

```
{
  "data_files_location": "s3://org-humancellatlas-dcp-test-data/10X-one-bundle/",
  "spreadsheet_location": "https://raw.github.com/HumanCellAtlas/metadata-schema/DEPLOYMENT/infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx",
  "expected_bundle_count": 1
}
```

**Comment by sampierson** [comment]
Done
