### ISSUE TITLE
Ingestion of pilot round of data

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#108]
We are wrangling in data for November.

Has new bundle structure, latest metadata.

DoD:
All data that is decided on for pilot is ingested into production

**Comment by kbergin** [comment]
Tracking here: https://docs.google.com/spreadsheets/d/155ACGfrgobXy9DI_GduYyHCpkCyFDIa6FvgH8keBdug/edit#gid=287685589

**Comment by morrisonnorman** [comment]
This issue is closed as it was completed for the Closed Beta release.
