### ISSUE TITLE
Enable metadata querying for the matrix service

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#109]
As the matrix service, I want to be able to do complicated metadata queries easily. A suggested implementation of this is the 'query module'. This is called "phase 3".

Link charter for suggested query module service here
[Draft design document](https://docs.google.com/document/d/1vHf1shvxmmUsCrbNWb8ABrEcQma2GKcQTSoPYDZ5vhY/edit)

**Comment by brianraymor** [comment]
Closing #109 and #110 in favor of a single epic #315 to reflect the change in our design.
