### ISSUE TITLE
Numerical filtering of DCP analysis matrix results

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#110]
As a user of DCP data, I'd like to be able to ask for only the data that meets certain numerical criteria. Without this capability, I must download or look into a lot more data than I need and will need to do filtering on my own. We are satisfying this use case through the matrix service and through standardizing analysis outputs in the DCP.

[Draft design document](https://docs.google.com/document/d/1vHf1shvxmmUsCrbNWb8ABrEcQma2GKcQTSoPYDZ5vhY/edit)

**Comment by brianraymor** [comment]
Closing #109 and #110 in favor of a single epic #315 to reflect the change in our design.
