### ISSUE TITLE
Concatenating matrices

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#111]
As a user of the DCP, I want to be able to browse the data portal and find the data that I want to study and then I expect to receive those analysis outputs all in one matrix so I can easily hand it off to a portal or download it for analysis. This is considered Phase 1 of the matrix service.

Edge cases:
What if a user's query has selected data that does not have analysis outputs i.e. no matrix

AC:
Analysis outputs in matrix format in the DCP can be concatenated and users receive it or are notified when it is ready
Users can hand off these matrices to viable tertiary portals or download the data
Documentation of the service and what it provides

**Comment by theathorn** [comment]
Data Browser:
https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/9
