### ISSUE TITLE
Capture interoperability of metadata within the metadata itself

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#114]
There is currently a significant issue within the DCP surrounding accommodating metadata changes. Both the Metadata API and the Ingest Client represent steps towards creating an interface between the metadata and the DCP and the users. This ticket represents an idea about a suite of tools and some changes to the metadata schema to capture metadata updates within the metadata, enabling other services to decouple from the schema. 

The metadata team are in parallel working to include deprecation information within the schema itself (e.g. ~`biological_sex`~ instead use `sex`).

This should provide support for ingest to automatically upgrade anything possible at the point of submission (so e.g. where submissions use older schema references) and for the datastore/data portal to automatically upgrade old queries to point at new fields, wherever possible.

This work has begun in https://github.com/HumanCellAtlas/metadata-api and  https://github.com/HumanCellAtlas/ingest-client

- [ ] Tony's RFC
- [ ] Tony add more tickets to this epic

**Comment by kbergin** [comment]
@tburdett can you link an RFC on this idea when you have one and then it could be a tech architecture discussion? Would love to prioritize anything that can help with the metadata decoupling for next Q across the DCP and we'll need more implementation details scoped out before then.

**Comment by tburdett** [comment]
First draft at an RFC for metadata evolvability: https://docs.google.com/document/d/1KpgPXqqnWCDqXDHMr1whmmCaT8XC2F7ddrDc0RPnyt4/edit#

**Comment by mweiden** [comment]
@kozbo ty

It would be great to also capture information about field _transformation_ in addition to the ones outlined in the [metadata deprecation policy](https://docs.google.com/document/d/1LWXbd652Tov7Kzw-tw6l5yFyo8BRh5FLMHZBfPOsgEY/edit#heading=h.1xqjmlvw392m). Some examples below.
* Changing the units of measurement on a quantitative measurement value
* Breaking a single url field into protocol, domain, tld, query path, query string ...

**Comment by theathorn** [comment]
@tburdett , what is the current state of this?

**Comment by tburdett** [comment]
I think this has been superceded by other ongoing efforts and discussions. The metadata evolvability document exists but has never made it to "official" RFC status in dcp-community repo due to a lack of consensus on the correct design or who might own any possible implementation.

I'd suggest closing or updating this ticket to reflect that further investigation and/or design work is needed

**Comment by brianraymor** [comment]
Closing per Tony's response.
