### ISSUE TITLE
Authentication, Authorization and Encryption

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#115]
As software engineers who are designing secure software, we should be using TLS encryption as well as authentication and authorization. This ticket is an Epic level ticket to track

**Comment by rhiananthony** [comment]
This is the document which came from the discussion between Tony, Rolando, Rodrey, Alegria, Norman, Parth, Trent

https://docs.google.com/document/d/19qWii-cL0mlzvZo_mqXjiJM7xXX8-gTojTleZHyudws/edit#

This was a great doc, but when we discussed this in the SecOps meeting, we decided that we need a little more in terms of implementation details.

**Comment by sampierson** [comment]
This epic is way to broad and covers at least 3 requirements.
It should be broken into 3 tickets, and have details added.
Except that we already have at least 2 of those tickets.  This is mostly just a duplicate.

**Comment by sampierson** [comment]
Covered by #99, #101, #102.
