### ISSUE TITLE
Current status and historical availability of public facing components is publicly available

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#130]
@mweiden has done a first pass at a status page to summarize the status of the DCP and its builds utilizing the work done in our health endpoint tickets and gitlab buildbox efforts. The page is public, although there is remaining work to make a user-aimed production only page. This epic represents the iterations we would like to do on this effort.

**Comment by kbergin** [comment]
From other ticket that I merged into this one: 
Currently, the status page Matt made represents status for all components internal environments (not prod). He recommends we make a public facing one that lets users know the system status. It can be on the same domain as the data portal but should not be on the data portal in case the portal is down.

Examples of other public facing status pages:
[GCP](https://www.google.com/appsstatus#hl=en&v=status)
[AWS](https://status.aws.amazon.com/)
[Azure](https://azure.microsoft.com/en-us/status/)

AC:
User facing prod status page exists

**Comment by mweiden** [comment]
This is done. https://prod.data.humancellatlas.org/system-status
