### ISSUE TITLE
Create a "Known issues" section for end users

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp#140]
## Problem
Users expect to find a list of known issues that can be searched through when they encounter a problem. Known issues often include instructions for work-arounds.

## DoD
Find a good location to publish and maintain a known issues list, and publish one.

the is a devops / support concern

**Comment by kbergin** [comment]
I think we could use the new `dcp-feedback` repo to file known issues. We could even list them in the readme of that repo and link to tickets. When I visit a product's bug filing page I always search to see if they already have a ticket on the bug so hopefully folks would do that too. Would that satisfy this?

**Comment by kozbo** [comment]
The trick is that we have several dozen repos that track issues. I wonder if there is a way to do a meta-search across multiple repos. Searches can be done at the org level with a little github knowledge.

The beta program will not be using the dcp-feedback repo going forward. This bug could be closed by building a knowledge base that is used in tier-1 support. We could create a user portal into this so that they could search too.
