### ISSUE TITLE
Update DCP integration test check for project shortname field 

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/dcp#155]
The DCP integration test is looking for the user-friendly field name "Project shortname" in the metadata spreadsheet and changing the value to be specific to the test (e.g. `integration/Smart-seq2/2018-10-11T20:01:08Z`): https://github.com/HumanCellAtlas/dcp/blob/master/tests/dataset_fixture.py#L42

Change this to `if project_tab['A4'].value != "project.project_core.project_short_name"`) since the user-friendly name may vary between spreadsheets.

**Comment by sampierson** [comment]
This is done, right @sahmanehsan?
I see code:
```
        if project_tab['A4'].value != "project.project_core.project_short_name":
            raise RuntimeError("Project shortname is no longer in cell project!A2")
```

**Comment by samanehsan** [comment]
Yes, this is done!
