### ISSUE TITLE
Dashboard for monitoring data progress through system

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#161]
From Tony: 
> Currently, pushing data through the HCA DCP requires considerable coordination, and a high degree of responsiveness between components. There is a tracking spreadsheet to monitor progress towards completion of these data journeys for 16 currently available single cell datasets, but so far processing through these journeys requires a number of manual interventions. Failures are not always reliably captured, data throughput is manually monitored across the system, and alerts are often missed in failure cases. In short, managing data throughput requires considerable shepherding by wranglers and developers.

Work on the automated scale test has yielded or will yield a more automated way to see progress of datasets through the DCP. An internally facing dashboard that tracks the progress of datasets on the submission level would help the DCP track production more easily.

**Comment by tburdett** [comment]
Further information provided by @parthshahva via email:

> Who is responsible for monitoring dataset ingestion/processing in production? I looked through some charters and did not see this responsibility explicitly defined. The motivation is that this week I noticed that a dataset (fetal/maternal interface) ingested in production a month ago had missing analysis bundles and duplicate analysis bundles. It seems that someone should explicitly own production data integrity/completion at least in this phase of the dcp. dcp-diag should allow non-developer users (wranglers?) to investigate this as well.
>
> Are wranglers responsible for monitoring both primary and analysis bundles plus indexing in azul? Is secondary analysis responsible for monitoring whether all expected workflows have run and produced bundles? Is there different ownership depending on whether the pipelines are "standard" or community pipelines? In a dream scenario, we would automate a lot of this and would have alerts when data count is unexpected. It will take time for us to get there though and will need accountability in the stop gap solutions.

**Comment by malloryfreeberg** [comment]
I think this is a really great idea, and having an automated dashboard would help significantly in tracking data integrity through the system.

I wanted to highlight a caveat in monitoring datasets in ingest. Currently, wranglers test uploading metadata spreadsheets and data files in ingest (usually staging for testing, but also production). We do this testing prior to getting explicit approval from the contributor that they are ready for their data to go to the public DS. So, we should be careful what from ingest gets put into a public-facing dashboard. I think analysis results coming back through ingest are OK (we can assume if the primary data are OK to be public, the rest are OK to be public, too).

I know the dashboard is not being worked on at the moment, but wanted to bring up my concern now :)

**Comment by claymfischer** [comment]
Very good point to be aware of @malloryfreeberg, thanks for bringing that up.

**Comment by zperova** [comment]
I am all hands up for the dashboard, as currently we (wranglers) do not have a way to check the submission of a dataset beyond the analyze-submission output. We can see and report whether the right amount of bundles has been exported and indexed, but we know nothing about the workflows for example. So the checks that wranglers can do stop at the primary bundles. Investigation of any type of error is also cumbersome at the moment - I think manual search through bad bundles via uuid is not the best use of the wrangler's time. 

I am not sure how useful such a dashboard will be for public view. I can see the value for showing contributor the progress of their own data through the system (something that has to happen once the programmatic submission is in place) - currently done via email communication. We do not have an agreed upon guideline of how many emails to send and what stages the contributors have to be informed of. Also I can see the value for a public dashboard showing the general status of all the datasets in the system (x datasets are undergoing analysis, x datasets are in the Browser, etc). Having an option for "Track your dataset" (as in tracking parcels) with project_label, project_shortname or assigned DOI in this public dashboard will kill two birds with one stone.

**Comment by malloryfreeberg** [comment]
I agree with @zperova that the dashboard is probably not so useful for general public view of the status of everything, but would be very useful for the data contributor of a given dataset. For example, a contributor submits a dataset then has an option to "track" it, with a similar view to the current tracker but for just the datasets they are authorized to see.

**Comment by parthshahva** [comment]
Currently the dashboard can be found at tracker.data.humancellatlas.org.

@zperova Unless I'm missing something, this seems to already meet most of your complaints about current visibility into projects 1) Insight into workflows 2) High level project view into all components (ingest, dss, matrix, azul, analysis) 3) Search by project_short_name or project_uuid

Right now, this dashboard is only being built for internal users (wranglers and other dcp members/developers to have insight into project status). There are no plans to add an authorization layer but can add if someone can explain the harm in this page being public. An initial set of user stories can be found at  https://docs.google.com/document/d/1f1AE1xftNlud_JsmF2idTEmHAN4vrHpnguji5s2wcNc. Please comment on the doc and let me know as you think of additional user stories

@zperova @malloryfreeberg I'd love to discuss how we can enable things like 1) tracking emails to submitters for their projects 2) Does this page need authorization? 3) How can we link projects to submitters 4) What other things would be useful?.  I have proposed a F2F session on this

**Comment by zperova** [comment]
> @zperova Unless I'm missing something, this seems to already meet most of your complaints about current visibility into projects 1) Insight into workflows 2) High level project view into all components (ingest, dss, matrix, azul, analysis) 3) Search by project_short_name or project_uuid
>
@parthshahva The tracker covers it all - thank you!

> @zperova @malloryfreeberg I'd love to discuss how we can enable things like 1) tracking emails to submitters for their projects 2) Does this page need authorization? 3) How can we link projects to submitters 4) Aggregrated stats on data moving through the system (discussion already started here with @sampierson) 5) What other things would be useful? I have proposed a F2F session for this discussion

Looking forward to your F2F session!

**Comment by theathorn** [comment]
@parthshahva Can we close this ticket and, if necessary, create new Epic(s) for any new issues?

**Comment by mweiden** [comment]
@theathorn the MVP of the tracker is complete. We'll create new epics for new work/improvements on it.
