### ISSUE TITLE
Tier 1: Create participant list

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp#163]
The plan is to start with the groups that have contributed data to the Beta program. But there has been a suggestion that we should include some of the red box community too.

**Comment by adriennes** [comment]
Spreadsheet here: 
https://docs.google.com/spreadsheets/d/12M4qYCCrVPjcH1XXjD5mIUub67dgdxRsfvHQkhX0Z50/edit?usp=drive_web&ouid=117879501772500659883
