### ISSUE TITLE
Help desk : set up help system

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp#170]

**Comment by kozbo** [comment]
Decide if we will be using an external service or creating our own.  

Either way, set up the help system

**Comment by kbergin** [comment]
We've decided to use the interviewer as the conduit for recording bugs and feedback and feature requests for Tier 1. They'll be recorded for future prioritization in `dcp-feedback` repo.

In Tier 2 we will need to scale via zendesk.
