### ISSUE TITLE
Define Reliability Requirements and implement tooling to track reliability/ fault tolerance

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#187]
This is an epic level ticket that is for the purpose of having each team define the reliability goals of their components of the project. This should include both uptime and fault tolerance.

**Comment by sampierson** [comment]
Covered by availability/SLO work.

**Comment by brianraymor** [comment]
Trevor has left a comment in ingest-central #229 Define Reliability Goals. I've closed other component issues that were part of this epic.
