### ISSUE TITLE
Evaluate Found Data

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#192]
We need to be able to provide users with a reliable experience when downloading data. In order to achieve this we need to understand how many users we can support concurrently accessing DCP user-facing components and how much data the DCP can support being downloaded.

See GA doc [here](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit?ts=5bf541fd#heading=h.mxvwuwmgfqkb)

**Comment by brianraymor** [comment]
This is similar to #191 - we need to update and refine with the tasks listed in the _Evaluate Initial Data_ user activity from the [Researcher with a keyboard](https://docs.google.com/drawings/d/1Li9o_uVkEZDZHbkQv86I49FG8I0zGSgHYkKabp7piEs/edit) and [Research with a pipette](https://docs.google.com/drawings/d/1o6I5BLtJuRJ1vUdb7dHCkFbo0XiaxKDBiVAogqnUowU/edit) journeys as a starting point. These are our basic user story maps. Trevor and I are currently working on a proposal for ZenHub process for review by PM on January 17 that would include this.

**Comment by theathorn** [comment]
Superseded by smaller more specific Epics.
