### ISSUE TITLE
Contribute My Data

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#193]
At present, the speed data moves through the DCP is inconsistent and as such we are unable to provide data contributors with any concrete estimates on how long before contributed data is available in the data browser. The end to end data flow process contains a number of uncertainties which presents difficulties in providing any estimates.

Potential metadata changes that will come with new data types adds an additional uncertainty to the process as our existing processes for assessing the consequences of metadata changes on downstream components such as display and analysis and requiring datasets which have failed due to errors involves a lot of manual interaction so the length of time it takes new data to come through the system is very depending on its novelty, complexity, overall size and number of data files.

See GA doc [here](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit?ts=5bf541fd#heading=h.t0a73b3c7y7c)

**Comment by theathorn** [comment]
Superseded by smaller more specific Epics.
