### ISSUE TITLE
M1: Provide uptime monitoring and downtime alerting of all user facing components

### ISSUE THREAD

**Issue by tburdett** [HumanCellAtlas/dcp#194]
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

**Comment by sampierson** [comment]
Closing in favor of
#281 Components provide a “health check” HTTPS endpoint
#282 Availability (“uptime”) of components is tracked
#130 Current status and historical availability of public facing components is publicly available
#65 Alerts are sent to dev/ops team for a component when it is down / unhealthy
#286 Operational logs for components are aggregated and retained for some time
#285 A dashboard of metrics is available for ops to monitor the aggregate activity of each component
