### ISSUE TITLE
M1.8: Ensure the data store outputs logs in enough detail to diagnose errors when reported

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp#199]
Relates to:
M1.8: Ensure the data store outputs logs in enough detail to diagnose errors when reported
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

@kozbo commented on [Fri Nov 30 2018](https://github.com/HumanCellAtlas/data-store/issues/1759)

## User story
* As a user
* I want to get a informative set of logs when I get an error
* so that I can diagnose the problem and take action to correct the error

Ensure the data store outputs logs in enough detail to diagnose errors when reported

## Definition of done
?

**Comment by morrisonnorman** [comment]
@kozbo  Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

**Comment by kozbo** [comment]
I think that this is done.
