### ISSUE TITLE
M2.4, M2.5: Ensure the data store and the matrix service can handle the expected number of concurrent requests from users

### ISSUE THREAD

**Issue by tburdett** [HumanCellAtlas/dcp#210]

**Comment by brianraymor** [comment]
@tburdett and @morrisonnorman - did you intend for this to be separate **Epics** for data store and the matrix service. Currently, I'm linking in our related issue as a dependency on this *simple* issue.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/matrix-service #184](https://github.com/HumanCellAtlas/matrix-service/issues/184) via [**ZenHub**](https://www.zenhub.com/)
