### ISSUE TITLE
M1.11: Ensure the matrix service output logs in enough detail to diagnose errors when reported

### ISSUE THREAD

**Issue by tburdett** [HumanCellAtlas/dcp#215]
Relates to:
M1.11: Ensure the matrix service output logs in enough detail to diagnose errors when reported
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

**Comment by morrisonnorman** [comment]
@brianraymor  Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

**Comment by brianraymor** [comment]
Linked in related issue. @parthshahva - are there any other issues that need to be referenced in this case? 105 was the issue that we were reporting for Logging in CBeta.

**Comment by parthshahva** [comment]
@brianraymor I think we're good to close this ticket. We've been able to diagnose problems to date with the current level of logging. If we encounter a problem in the future that can't be debugged, we will create a ticket in the matrix service repo to fix the logging
