### ISSUE TITLE
M1.6 Ensure that submitters are notified on the progress of their submission through the DCP (e.g. ingested, stored, analysed, available in the browser)

### ISSUE THREAD

**Issue by tburdett** [HumanCellAtlas/dcp#217]
This Milestone relates to Task:
M1.6: Ensure that submitters are notified on the progress of their submission through the DCP.

[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

At present, the speed data moves through the DCP is inconsistent and as such we are unable to provide data contributors with any concrete estimates on how long before contributed data is available in the data browser. The end to end data flow process contains a number of uncertainties which presents difficulties in providing any estimates.

Potential metadata changes that will come with new data types adds an additional uncertainty to the process as our existing processes for assessing the consequences of metadata changes on downstream components such as display and analysis and requiring datasets which have failed due to errors involves a lot of manual interaction so the length of time it takes new data to come through the system is very depending on its novelty, complexity, overall size and number of data files.

**Comment by kbergin** [comment]
I'm unclear on if analysis needs to do anything for this. We are currently adding functionality to the dcp-diag tool to provide more information on analysis status, perhaps that will be sufficient for notifying submitters on request? Or if we are automating something, it seems like we'd need a technical design and plan for this and probably the same functionality leveraged in the dcp diag tool could be used. 

I'll link our ticket for the dcp-diag tool for now.
