### ISSUE TITLE
M1.7: Ensure the ingestion service outputs logs in enough detail to diagnose errors when reported

### ISSUE THREAD

**Issue by tburdett** [HumanCellAtlas/dcp#220]
Relates to:
M1.1: Provide availability monitoring and downtime alerting of data portal.
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

**Comment by morrisonnorman** [comment]
@justincc Can you comment on the status of this epic please and link any open issues you are currently working on.

**Comment by justincc** [comment]
Complete
