### ISSUE TITLE
M1.2: Provide availability monitoring and downtime alerting of data browser

### ISSUE THREAD

**Issue by morrisonnorman** [HumanCellAtlas/dcp#231]
Relates to:
M1.2: Provide availability monitoring and downtime alerting of data browser.
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

**Comment by morrisonnorman** [comment]
@theathorn Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

**Comment by theathorn** [comment]
Issues linked.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/data-browser #451](https://github.com/HumanCellAtlas/data-browser/issues/451) via [**ZenHub**](https://www.zenhub.com/)
