### ISSUE TITLE
Define integration test improvements to exercise metadata schema changes and updates

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/dcp#232]
## Need

Metadata schema changes are not currently tested against existing DCP systems that depend on the schema, which results in system failures at time of data submission. In order to avoid these failures, we need to test metadata schema changes before deployment.

## Scoping Task

This work is not yet well-scoped. To refine requirements.

- [x] Consult with Metadata team on [Phase 1 and Phase 2A](https://docs.google.com/presentation/d/1Y28vT6PbPDC6ublsZIIMNTvianCxVLlt4M5sypwX2wE/edit#slide=id.g4339acaf8a_0_46) of the schema robustness plan and gather information on integration test design
- [x] Revise metadata schema integration test RFC and submit to `dcp-community` repo
- [x] Once approved, help teams create tickets for their boards that reflect the plan laid out in the RFC

**Comment by theathorn** [comment]
Waiting for RFC approval.
