### ISSUE TITLE
Define required granularity of financial tracking data and define spending objectives

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/dcp#235]
## Need

Track financial details, including the total spend incurred by usage of the DCP in production conditions.

## Scoping Task

Write a spec that details what requirements we need to fulfill for funders and for development purposes.

**Comment by mweiden** [comment]
See spec below

https://docs.google.com/document/d/1zYvC6vBZMm7CC01ET_mBeWDVrxcGYBSqqBMWqdMqYCE/edit#

**Comment by theathorn** [comment]
See also #78.
