### ISSUE TITLE
Define reanalysis bundling strategy

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/dcp#236]
## Need

Ensure that new analysis results resulting from reanalysis of existing data are propagated to the datastore and take precedence over the previous analysis results.

## Scoping Task

- [ ] Finish and refine the spec for [Updating metadata](https://docs.google.com/document/d/1XeAw05RAJe20Q1XDF7eLWLGF3gCme4-8l-ZfhtDWOLg/edit#heading=h.d359hn1fcvx). Optional: publish it as an RFC in the `dcp-community` repo.
- [ ] Help teams that have work resulting from the RFC define tickets.

**Comment by justincc** [comment]
As discussed (though not yet with you @morrisonnorman! Let's talk after the hols) I am bouncing this to @morrisonnorman to really nail down the requirements before taking up the technical aspects.

**Comment by justincc** [comment]
Linked to #234

**Comment by theathorn** [comment]
Linked to #224.

**Comment by justincc** [comment]
The current strategy is that we simple re-ingest the whole project. This will lose any provenance. This may be tweakable by at least keeping the same project UUID even if all the bundles are completely different. This will require tombstoning the old bundles or updating them to show they are now obsolete (as per @diekhans).

**Comment by theathorn** [comment]
I am concerned that re-ingesting a whole project and tombstoning the old data would make data citations (see #226) not viable.  i.e. Scientists who cite DCP data in publications expect the reference to that data and the cited data itself to remain unchanged. I would like to hear Tech Architecture's view on this problem.

**Comment by xbrianh** [comment]
Our update process should probably not have the side effect of making data disappear. This is problematic for citations, as @theathorn noted, and I don't think it's technically necessary.

**Comment by diekhans** [comment]
I was under the impression that reingestion was a one-time thing.

One we go public next month, it would be really bad to reingest.  it is far better to have inconsistent metadata and project that do not update than to lose provenance.

However, note that is is about reanalysis, which may or may not get a new UUID dependent on policy.  However, the previous analysis must remain.

**Comment by claymfischer** [comment]
In a perfect world this recent reingestion would be the last time, but realistically full implementation of AUDR won't be available immediately. There may be circumstances requiring some amount of reingestion we are unable to predict at this time.

From this point forward, if a situation occurs requiring reingestion, it is **imperative** that anything released 'to the wild' never disappears. It must be citable and accessible at a URL - ideally in perpetuity.

Mike Cherry (@jmcherry) has also emphasized this.

**Comment by diekhans** [comment]
@claymfischer what are the circumstances that would require reingestion?

**Comment by sampierson** [comment]
I think the big 3 are:
* Metadata correction
* Data correction
* Pipeline correction/changes
Am I close?

**Comment by claymfischer** [comment]
"There may be circumstances requiring some amount of reingestion we are unable to predict at this time." - maybe something an early AUDR implementation is unable to resolve.

**Comment by diekhans** [comment]
>   Am I close?

Very.  although I would argue that even in these cases unless it is scientifically really bad, to avoid reingestion.  If desperate, it would be "additional ingestion".  Create a newer project and leave the old one there.  Maybe avoid displaying in the browser.

Redaction of data, well, you do purge the data and leave the metadata. Do manually.

Redaction of metadata (yes this can happen);  Manually edit the DSS .

**Comment by xbrianh** [comment]
> Redaction of data, well, you do purge the data and leave the metadata. Do manually.
> 
> Redaction of metadata (yes this can happen); Manually edit the DSS .

Would an example of redaction be data where consent has been revoked? My understanding is that the DSS should support permanent deletion for these cases.

DSS objects may be updated with a new version, tombstoned, or deleted. Other than that, I'm not sure what "editing" would mean.

**Comment by jahilton** [comment]
> I think the big 3 are:
> 
> * Metadata correction
> * Data correction
> * Pipeline correction/changes
>   Am I close?

Schema updates also require re-ingestion?

**Comment by diekhans** [comment]
> Schema updates also require re-ingestion?

Currently, there is no fully working mechanism for update metadata or data in the system

To try to summarize my view since this is drifting.
 
1. Re-ingesting was a short-term hack to move various development activities forward.  It is neither part of a design or an SOP. 
2. Once the site goes officially live next month, we should not reingest unless it is an emergency.  Even then, we need to keep the old data around (unless redacted), despite any pain and confusion.
3. We need to all work towards getting a complete update mechanism working to support scientific requirements.

**Comment by diekhans** [comment]
> Would an example of redaction be data where consent has been revoked? My understanding is that the DSS should support permanent deletion for these cases.

Yes, redaction is when we are not legally allowed to have the data. Data never being properly consented in the first place.  Personally identifiable information accidentally being added to metadata sometimes happens.

In all cases, we need to remove the data completely, but still being able to inform users it was redacted, rather than just `not found'.

**Comment by theathorn** [comment]
@diekhans "reingest ... we need to keep the old data around". Not sure how that would work. We don't want 2 copies of a project (i.e. the same project with different project UUIDs) in the "live/latest" view as they will be counted twice in the Data Browser. Proper versioning would allow us to show the "latest" and "previous releases" views (Azul currently only indexes the latest version of files but we have started discussing the needed changes to support versioning / data releases).

**Comment by diekhans** [comment]
@theathorn  I would work rather rather badly.  The browser would have to put in some kind of ugly hack to not display the old project, like the uuid hard coded?

But this would be an emergency anyway and it would go away

**Comment by justincc** [comment]
@diekhans I accidentally thought this was about re-ingestion. It is indeed about re-analysis which would either be a new analysis where >=2 analysis bundles would have the same parent primary bundle or reanalysis (as is the case here), which will be an updated where an existing bundle in the datastore gets a new version. In both cases it is up to analysis to tell us what they want and there will be a mechanism for them to do so.

**Comment by justincc** [comment]
If there is experiment structure change then the only current available action, as [@lauraclarke has previously said](https://github.com/HumanCellAtlas/dcp/issues/226#issuecomment-484437348) is to re-ingest. As it is, this will break provenance and generate a new project UUID. However, we could probably make the new structure a new submission to the project and tombstone the previous submission, which would keep the project UUID. This will still break provenance unless the reason for change is kept in a file that remains in both submissions such as the file that stores the project metadata. If we want to explore this solution then it should be added to 2019Q3 AUDR asap unless it's acceptable to push off to Q4.

**Comment by justincc** [comment]
@jahilton We are coming up to the point where simple metadata updates (those that are changing existing fields) will start becoming reality. In Q3 we are scheduled to also allow addition of data (and implicitly I guess data update - this is not something that was in Q2!). Add/remove of fields (schema update) is probably a simple addition from ingest's point of view, albeit sometimes one with a large delta. The big issue is structural change where it's extremely difficult/impossible to establish relationships between changing bundles.

This was explored in [the Feb 2019 F2F](https://docs.google.com/presentation/d/1HdxOY8kExTuSNFwcrK_YenXQOkDJR49Y1CCtFCh2Zu8/edit#slide=id.g4e2ead9549_0_20)

**Comment by justincc** [comment]
Included within #416
