### ISSUE TITLE
M1.3: Provide availability monitoring and downtime alerting of matrix service

### ISSUE THREAD

**Issue by morrisonnorman** [HumanCellAtlas/dcp#239]
Relates to:
M1.3: Provide availability monitoring and downtime alerting of matrix service
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

**Comment by morrisonnorman** [comment]
@brianraymor  Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

**Comment by brianraymor** [comment]
This was addressed in the linked issue.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/matrix-service #183](https://github.com/HumanCellAtlas/matrix-service/issues/183) via [**ZenHub**](https://www.zenhub.com/)
