### ISSUE TITLE
 M1.9: Ensure analysis pipelines output logs in enough detail to diagnose errors when reported

### ISSUE THREAD

**Issue by morrisonnorman** [HumanCellAtlas/dcp#241]
Relates to:
M1.9: Ensure analysis pipelines output logs in enough detail to diagnose errors when reported.
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

**Comment by morrisonnorman** [comment]
@kbergin  Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

**Comment by kbergin** [comment]
@samanehsan @rexwangcc what is your opinion here - do we output enough logs to satisfy this requirement or should we decide on a scope of improvement we want to add? I think last we talked we said it was sufficient for this milestone's purposes but I want to confirm here.

**Comment by rexwangcc** [comment]
@kbergin Based on our discussion last time, and the fact that we have managed to use the logs we generate to debug for the CBeta phase and scaling tests, I believe it's sufficient!

**Comment by kbergin** [comment]
Excellent, we will consider this done, then. Closing now.
