### ISSUE TITLE
Health check should return 503 status if any components are down

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp#248]
The 503 should still carry a JSON body, same as a 200 response.

**Comment by brianraymor** [comment]
@hannes-ucsc and @tburdett - is this intended to be a requirement for the [Provide uptime monitoring and downtime alerting of all user facing components](https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/194) Epic?

**Comment by mweiden** [comment]
@brianraymor yes, this could be nested under that epic

**Comment by theathorn** [comment]
@mweiden I've moved this item into #61 which is under Epic #65 (which needs consolidation with Epc #194).
