### ISSUE TITLE
Add security.txt file to all repos

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#274]
Add a security.txt file to all repo.
This is as a way for people to communicate security issues to us.
Albano is writing the first one, then we will add it to all repos.
security.txt contents:
```
If you'd like to report a security issue please contact us
Contact: security-leads@data.humancellatlas.org
```

**Comment by kislyuk** [comment]
The [security.txt standard proposal](https://securitytxt.org/) specifies adding security.txt to a path on the HTTP server endpoint, *not* to the repo.

In keeping with standard repo conventions, the corresponding file in the repo should be called SECURITY.md, not security.txt.

@DailyDreaming, I know you have been sending PRs to various repos. Can you please adjust your contributions to match the above?

**Comment by kislyuk** [comment]
Also, the SECURITY.md file, if present in the repo, should be called out in the main README.md file under a "#Security Policy" header.

**Comment by kislyuk** [comment]
Good examples SECURITY.md file contents can be found here:

* https://github.com/standard/standard/blob/master/SECURITY.md
* https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md#vulnerabilities-in-tensorflow

**Comment by kislyuk** [comment]
Finally, instead of placing a file in each repo, I would suggest that all service repos reference a single SECURITY.md file in a central location, for example https://github.com/HumanCellAtlas/dcp/blob/master/SECURITY.md.

**Comment by sampierson** [comment]
@adrazhi is this what you meant in your requirement?

**Comment by adrazhi** [comment]
@sampierson @kislyuk 
The important thing here is to allow external folks to have a way to reach out in case anything is found.  Examples that Andrey mentioned are good however a bit more verbose since they're targeted at researchers who actively work on finding security issues in such libraries. That said, you can certainly use it. 

Second, I have no strong opinion on the below - either way is fine. 
> Finally, instead of placing a file in each repo, I would suggest that all service repos reference a single SECURITY.md file in a central location, for example 


Third, given that the repos are open source, it's a good location to host the security contact info.

**Comment by DailyDreaming** [comment]
@kislyuk Yes, I can do so.

For record keeping, the following repos have the basic `security.txt` initially proposed:
- [x] lira
- [x] matrix-service
- [x] skylab
- [x] dcp-cli
- [x] datastore
- [x] dcp
- [x] fusillade
- [x] dcp-diag
- [x] data-portal
- [x] data-browser

I'll use the above link as a template and submit post a draft here for criticism.

**Comment by DailyDreaming** [comment]
@kislyuk @adrazhi @sampierson I've borrowed liberally from the tensorflow `SECURITY.md` (Apache 2 license) and created a PR here for the `data-store` for comment: https://github.com/HumanCellAtlas/data-store/pull/1977

**Comment by DailyDreaming** [comment]
@kislyuk @adrazhi @sampierson Could I get someone to take a look?  ^

**Comment by rhiananthony** [comment]
This has been completed for all repos owned by secondary analysis

**Comment by brianraymor** [comment]
@rhiananthony, @stahiri - who is the shepherd for DevSecOps for this issue? All items in the Product Backlog need an owner.

**Comment by stahiri** [comment]
Have child issues been created for tracking across all repos?

**Comment by brianraymor** [comment]
@stahiri - DCP has adopted ZenHub because it supports epics and other features. If you look in - https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/274 - you'll see the child issues that were created.

**Comment by brianraymor** [comment]
@stahiri - not sure why this in *In Progress* in *General Availability*.  Is this going to be closed in Q3?

**Comment by stahiri** [comment]
Associated with the Q3 release, closure pending confirmation that the final ingest ticket is complete

**Comment by brianraymor** [comment]
@stahiri - Should this be set to Q4M3 to match the schedule for the pending ingest issue?

**Comment by stahiri** [comment]
@brianraymor yes, thanks for the assist! This has been updated.

**Comment by stahiri** [comment]
As discussed in the 9/25/19 DevSecOps meeting, all repos will reference security.md via the issues and security tabs. Repos may elect to additionally include a security.txt file and are responsible for ensuring that: (1) security.txt references the overarching HCA security.md, and (2) paths to security.md are kept up to date in the security.txt file.

Given this, I'm closing this ticket.
