### ISSUE TITLE
Ensure secrets do not leak into source code

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#277]
Verify that all developers are using Git Secrets.

https://github.com/awslabs/git-secrets
https://cloud.google.com/blog/products/gcp/help-keep-your-google-cloud-service-account-keys-safe
https://docs.google.com/document/d/1_7deaZd2XbjUetVJs8EsQg6JbW_MEX2iFgXpnR_PyYs/edit#heading=h.4f1e34ah25ia

**Comment by diekhans** [comment]
The cited document does not allow copying or saving of text, thus one must type these command in by hand.   Have a script everyone runs would make it more likely for this to happen and be correct.

**Comment by xbrianh** [comment]
See also our in-house git-secrets documentation:
https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Git%20Secrets

@diekhans

**Comment by stahiri** [comment]
Closing this iceboxed ticket as all supporting child tickets are complete
