### ISSUE TITLE
MVP for improved metadata access for the end user

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp#279]
As a user I want a simpler, more accessible way to see the metadata associated with my faceted search query.
There are multiple issues with the current approach:
  - The JSON files provided by the cli download manifest command are hard to navigate.
  - There are many files whose inter-relationship is not clear.
  - The first-level directory names are bundle UUIDs, which have no meaning to the user.
Proposed improvements:
  - Add all indexed metadata fields to the file manifest
  - Show all available metadata fields in the Projects detail page
  - Generate a per-project metadata tsv file that can be downloaded directly from the Data Browser Projects tab

NOTE: we are working on the definition of this epic in the following doc: https://docs.google.com/document/d/1u2OOkqnKtVKUhg-yWowuUco_P-A4p8VBx0oAai7E8aU/edit?usp=sharing

**Comment by claymfischer** [comment]
It's wonderful to have metadata available at a project level and will aid data consumers immensely.

Something mentioned but I am unsure has been discussed in detail: most DCCs return records (rows, generally representing an individual file) which are clickable. If you click into one of those records, you can see all metadata associated with that record. This allows users to learn all about a record (file) without having to download anything, and without making the UI unusable from having too many columns of metadata displayed.

This is a bit complicated on the HCA as rows are returned at different entity levels beyond file. A judgement call may have to be made to only implement this for one entity.

@adriennes @gabsie @matthewspeir may have more input on if it merits further discussion as part of this epic.

**Comment by theathorn** [comment]
2 issues remaining (In Progress). Targeting release to prod next week.
