### ISSUE TITLE
Availability (“uptime”) of all DCP components is tracked

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp#282]
Current status and availability numbers are made available for consumption by DCP development and operations folk.  This is already in place at https://humancellatlas.github.io/ for all components except the following:
- [x] metadata
- [x] Azul
- [x] Data Portal

**Comment by sampierson** [comment]
Removing "Data Browser" from the to-do list.  It is just a javascript app and doesn't have a monitorable server-side component.

**Comment by sampierson** [comment]
Also https://github.com/HumanCellAtlas/humancellatlas.github.io/issues/1 but that repo is not connected here.

**Comment by brianraymor** [comment]
@sampierson - humancellatlas.github.io is connected now.

**Comment by stahiri** [comment]
This ticket appears to be complete. Closing.
