### ISSUE TITLE
Operational logs for components are aggregated and retained for some time

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp#286]
Logs should contain sufficient detail to support debugging.
Logs should be aggregated and viewable at https://logs.data.humancellatlas.org/
Yes "some time" is not defined here.  The logging system has a policy for that.

- [ ] Metadata
- [x] Ingest
- [x] Upload
- [x] Data Store
- [x] Analysis
- [x] Matrix
- [x] Azul
- [ ] Browser?
- [ ] Portal
- [x] Logs
- [x] Metrics

**Comment by brianraymor** [comment]
@stahiri - not sure why this in *In Progress* in *General Availability*. Can the release be cleared and this issue sent to the Icebox?

**Comment by parthshahva** [comment]
@mweiden can't this ticket be closed? It seems this should be set up for all components

**Comment by mweiden** [comment]
Yes, we can close this ticket. @stahiri and I should sync and determine if all of the retention periods are correct, but we can handle this in a separate thread.
