### ISSUE TITLE
Research PaaS financial tracking tools, design tag schema

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp#302]
We need to monitor our spending and find ways to improve where possible. Here are the high-level requirements from Jonah: https://docs.google.com/document/d/1zYvC6vBZMm7CC01ET_mBeWDVrxcGYBSqqBMWqdMqYCE/edit#

Coverage is required In both AWS and GCP.  Need to be able to break spend down by DCP component, and by service type (bucket storage, compute, batch, etc).

In AWS I believe this requires we tag each of our resources and then use their finance tools to mine those tags and aggregate costs.  Not sure how this works in GCP.

Step 1 = research the different mechanisms in AWS / GCP.
Step 2 = design tagging strategy, detail it in the dcp repo ticket #78 (https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/78)
Step 3 = ping component teams to implement their part
Step 4 = ensure platform-wide tools work as advertised

**Comment by sampierson** [comment]
@kislyuk this ticket "Research PaaS financial tracking tools, design tag schema" is part of a the epic #78 (Track financial details, including the total spend incurred by usage of the DCP in production conditions).  Any interest in doing this research part?  I recall you exploring this area before.

**Comment by kislyuk** [comment]
@sampierson Yes! I'm working on some solutions for this, and want to find better tools for it.

**Comment by kislyuk** [comment]
(The solutions I'm working on revolve around auto-tagging of resources, and the CZI shared infra team has something for that too, though I'm not sure if it will be directly applicable. Other tools for identifying and tracking cost drivers will be needed as well.)

**Comment by kozbo** [comment]
Is this issue complete now that the tagging RFC has been adopted?
https://github.com/HumanCellAtlas/dcp-community/pull/75/files

**Comment by kislyuk** [comment]
Yes, complete now.
