### ISSUE TITLE
Decide what tools to use for leaked secret detection

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp#307]
The DevSecOps team needs to decide what static/dynamic analysis tools to encourage/mandate.
Then we will tell all the component teams to use them.

**Comment by sampierson** [comment]
So @adrazhi or @stahiri: Is Trufflehog the answer to this question?  Can we state that, close this and unblock #91?

**Comment by adrazhi** [comment]
@sampierson I think it'd be better if we keep this issue related to the following: 

1. Security static code analysis tools to use, e.g Codacy, Checkmarx etc. 
2. Dynamic analysis tools (pentest) such as Burp or ZAP. 

Trufflehog is for searching for any secrets committed accidentally that have bypassed the client side protection provided by git-secrets.

**Comment by sampierson** [comment]
Okay now you made me punch the wall and my hand hurts.

The way this system work is:
1. There is an EPIC ticket.  That is the umbrella for an issue.
2. There are many tickets in other component repos under the epic to perform work to complete the epic.
3. If research is required before we can proceed, that is a ticket in the dcp repo, marked as a blocker for the epic.

In this case:

* #91 is the EPIC
* There are many tickets attached to that epic.
* This ticket (#307) is the research ticket for that epic AND IS BLOCKING IT.

Now you just got me to rename epic #91 from "Source code static & dynamic analysis" to "Detect secrets that have leaked into source code".  Not you want to leave that blocked by this ticket with has a much broader focus?  THIS MAKES NO SENSE.

**Comment by sampierson** [comment]
@adrazhi are you actually looking at these in ZenHub or GitHub?  Perhaps that is the source of the confusion.

**Comment by adrazhi** [comment]
@sampierson My bad, I got confused by the static/dynamic terms and forgot that it's specifically to this. Then going back to your original question, the answer is yes. 

Original question
> So @adrazhi or @stahiri: Is Trufflehog the answer to this question? Can we state that, close this and unblock #91?

**Comment by sampierson** [comment]
Great! Thanks!

Okay I think there may be a need for different tickets that address Codacy, Checkmarx and
Burp or ZAP.  For now let's rename this to match its epic and then close it so we can move forward and unblock the epic.

**Comment by sampierson** [comment]
Per @adrazhi we should use Trufflehog.  Closing this.
