### ISSUE TITLE
decide which tool(s) to use to determine 3rd party library security flaws

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp#308]
DevSecOps team needs to decide which tools to use.
Then we will update all component tickets with this information.
There has been talk of Snyk and SourceClear, and apparently GitHub has some builtin functionality here too.

**Comment by stahiri** [comment]
DevSecOps recommendation is for everyone to use the same tool. Both Snyk and SourceClear are good options here. Prior recommendation from the team is to start with Snyk since it's open source.

**Comment by brianraymor** [comment]
@stahiri - @sampierson wrote _DevSecOps team needs to decide which tools to use.
*Then we will update all component tickets with this information*._ Could you make the appropriate updates?
