### ISSUE TITLE
OpSec

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#32]
To ensure our operations are secure, we should consider things like: Git Secrets, PullApprove on “production” push and the modification of sensitive files, ubiquitous two factor authentication (2FA), how to establish centralized access control for developer provisioning (adding new devs and proper roles) and termination (when they leave their organizations).

**Comment by brianraymor** [comment]
@kbergin - do we need this epic anymore?

**Comment by sampierson** [comment]
This epic is being broken into other epics at the direction of the DevSecOps team.
