### ISSUE TITLE
Delete all bundles from projects mentioned in Azul's project suppression list

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp#320]
The Azul team is maintaining an ever-growing [project suppression list](https://github.com/DataBiosphere/azul/blob/55670a4b1c917ccd7d925e70639ef54e9ece8262/src/azul/project/hca/__init__.py#L96). Any user NOT using the data browser will still see those projects and nothing would indicate to them that those projects are now obsolete and have been superseded by  replacement projects of higher quality. This will cause pain and confusion after GA.

We should delete (aka tombstone) all bundles belonging to projects on that list from the DSS before GA.

This should be done in staging and production.

**Comment by hannes-ucsc** [comment]
We should also physically delete the failed attempts of indexing Tabula Muris. Those make up around 300k redundant bundle versions.

**Comment by kozbo** [comment]
see data store #2139

**Comment by brianraymor** [comment]
@theathorn - Who is the appropriate owner and what is the rationale for including this on the dcp-level - since there are no dependencies noted?
