### ISSUE TITLE
Race in data browser test may prevent all bundles from being deleted

### ISSUE THREAD

**Issue by jessebrennan** [HumanCellAtlas/dcp#324]
The race occurs because [`_assert_data_browser_bundles()`](https://github.com/HumanCellAtlas/dcp/blob/2ab76d1ef70e48c438924670bae60319978f701d/tests/dataset_runner.py#L223) Waits until **at least one** file from each bundle is present, but not for **all** files from both bundles to be present. This means that some files may not be indexed before the deletion notification is sent. Thus these files will still be present in the index and Azul's cleanup assertion will fail.

This is what's responsible for this failure https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/23210

The planned solution is to count the number of files referenced **per** bundles on a run that did not clean up. This number will be hard coded and `_assert_data_browser_bundles()` will be amended to check that the number of files referenced **per** bundles is the same.

**Comment by hannes-ucsc** [comment]
@jessebrennan, the ticket remains assigned to the person authoring the PR. Only the PR changes assignees.

**Comment by jessebrennan** [comment]
My mistake, I must have been spacing out when I did that.
