### ISSUE TITLE
Trufflehog Checklist.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/dcp#325]
Trufflehog has some PRs and will be implemented for a few repos.  This ticket is just to ask for some oversight from DevSecOps ( @sampierson @adrazhi @davidbernick ) on a few points:
- Is the [regex list we've added](https://github.com/HumanCellAtlas/dcplib/blob/master/components/trufflehog_regex_patterns.json) sufficient?
- Which repos should trufflehog checking be added to?  (See the [data-store implementation](https://github.com/HumanCellAtlas/data-store/pull/1985) )
- Trufflehog currently only checks regex.  High entropy string matching seems to pick up a lot of noise (pages and pages in the data-store).  Is the high entropy string matching something we should put effort into leveraging?

**Comment by brianraymor** [comment]
@DailyDreaming and @sampierson  - is there a relationship between this issue and https://github.com/HumanCellAtlas/dcp/issues/307 and https://github.com/HumanCellAtlas/dcp/issues/91 ?

For example, from #91:
_There has been talk of running trufflehog, a tool to find embedded secrets in code before it is pushed._

**Comment by adrazhi** [comment]
@DailyDreaming 

- The regex list seems good. 
- Ideally all repos, have a job that does weekly scans 
- High entropy string matching does pick up a lot of noise so until we think of a better way or solution to handle this you can focus on regex support for now

**Comment by DailyDreaming** [comment]
@adrazhi This checks every commit made to `data-store` so I think that that more than meets the once a week req.

I'll add it to the `dcp-cli` to do the same and the other repos I added our security policy to.  For me that means:

- [x] lira
- [x] matrix-service
- [x] skylab
- [x] dcp-cli
- [x] datastore
- [x] dcp
- [x] fusillade
- [x] dcp-diag
- [x] data-portal
- [x] data-browser

Though it might be good to create a wider range of issues in `dcp` like was done for the `security.txt` file to address all of the repos of interest:
https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/274

**Comment by kozbo** [comment]
@stahiri How is the appropriate owner and what is the status of this? Should it be part of Sprint 3 to be complete by the end of the month?

**Comment by stahiri** [comment]
I'll take accountability. I do believe this should be completed for Q2 (so included in Sprint 3) given that this ticket predates my history with DCP.

**Comment by DailyDreaming** [comment]
@stahiri Let me know if the trufflehog regexes are sufficient.  I got the impression that we only owned responsibility for the implementation of this in the `data-store` and `dcp-cli`, but let me know if I can help out with this in any way.

**Comment by DailyDreaming** [comment]
@stahiri That sounds accurate to me.  Closed.
