### ISSUE TITLE
Enabling easy reuse of the DCP

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#33]
There are many projects that could reuse the DCP software. NeMO has attempted to reuse both blue and purple, and identified a lot of great feedback. As a part of the data biosphere efforts, it is critical that we make our software easy to deploy and use for other projects. 

A reusable DCP component would have
- ease of deployment
- clear documentation
- clear contributions methods as open source products
- clear way to submit bugs, issues, feedback
- be generalizable

**Comment by theathorn** [comment]
Closed as non-actionable by repo review committee.
Specific Nemo requirements would be a separate ticket.
