### ISSUE TITLE
Persistent lists of data

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#34]
As a user of the DCP, I will approach it and it's vast amounts of data and, after searching for the data that meets the requirements of my study or analysis, I will want to take those search results and treat them as a unit. 

A user can create a persistent list of data, view existing lists, export or download the list. This feature is analogous to a shopping cart capability on an e-commerce site. 

AC:
- [ ] Data Browser
- [ ] Use cases document is updated

[NOTE: this used to be called collections using a persistent store for temporary user lists didn't make sense. We will use a shopping cart for user lists and collection for data releases.]

**Comment by kozbo** [comment]
Moving this to Backlog as we will not work on it until we get beyond Pilot.

**Comment by theathorn** [comment]
Data Browser:
https://app.zenhub.com/workspace/o/databiosphere/azul/issues/88

**Comment by kozbo** [comment]
@theathorn : please add information and links too the shopping cart feature in the Browser

**Comment by kozbo** [comment]
@theathorn moving this to you. This ticket seems a little confused as it talks about shopping carts but the tasks are collections.

**Comment by theathorn** [comment]
Needs clarification and prioritization from PLs and UX - not in Q3 RACI matrix.

**Comment by brianraymor** [comment]
@theathorn - can this simply be closed. We can _make more_ when it becomes a priority. Otherwise, _iceboxed_?
