### ISSUE TITLE
Data hand-off to selected tertiary portals

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#35]
Status as of 11/5/19: UCSC Xena integration added
Status as of 10/7/19: scope is now Terra and SCEA; SCP has been removed.

We want to avoid users downloading data from the DCP by enabling them to access the data in various portals to perform their analyses. This requires the ability to handoff data from the data browser to tertiary portals.

API specification: https://editor.swagger.io/?url=https://raw.githubusercontent.com/DataBiosphere/azul/issues/hannes/1197-portal-api-spec/rfc/portal-registration-api.yaml

**Comment by theathorn** [comment]
Need to generate a proposal and identify a set of tertiary portal developers to review.

**Comment by theathorn** [comment]
For Q3 I'm setting the scope of this work to cover hand-off to a select few "early adopter" portals:
  - Terra (already covered under #337)
  - The Broad Single Cell Portal
  - EBI Single Cell Expression Atlas

For SCP and SCEA we will implement a simple "project_uuid" hand-off mechanism that will allow each portal to display vizualizations for that specific project.

**Comment by theathorn** [comment]
On track for Q3 support of SCP and SCEA, but noting there are external dependencies here.

**Comment by theathorn** [comment]
Work in progress will now complete in Q4M1.

**Comment by theathorn** [comment]
The project contributors for "Ischaemic sensitivity of human tissue by single cell RNA seq" state that it is not complete and they will be adding more data. Consequently SCP has stated that they no longer wish to link to this project and that "We are looking to the general policy for HCA data and its implications on SCP studies".
