### ISSUE TITLE
Data consumers can get access to the most important metadata from one specific project in a digestible format

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp#356]
**Overview:** Data consumers can get access to the most important metadata from one specific project in a digestible format.

**User Story:** As a researcher with a keyboard, I want to obtain all the metadata for a project, so that I can get a feel for how much data there is in this project that is of interest to me

**Delivery at the end of Q2:**  Establish a first iteration of metadata accessible for download and demonstrate downloading that metadata through the data browser for a 1) project and additionally for 2) a sample (specimen?).  The filter by sample can be done through CLI tools.

**Out of Scope for Q2:**
  - full metadata API for users that hides the underlying json complexities
  - arbitrary metadata tsv generation per user query

**Evaluation Plan - how this will be evaluated at the end of the quarter:**  1) There is a tutorial (on or pointed to from our “Guides” portal section) that a researcher can follow that will show them how to 1) navigate to and understand project pages including what the metadata download link does and 2) search and locate a sample (specimen?) page that includes a link to the same metadata bulk download file but filtered to only show the current sample.  The filter by sample can be done through CLI tools.

**Needs from Responsible Groups:**
* Laura - Metadata
  * Stable metadata and a script that will generate a metadata dump across all files in the Data Store -- DONE, handed off to orange box folks
* Brian - Data Browser/Data Store
  * The project page needs links to metadata dumps in TSV (and optionally JSON) structure -- DONE for TSV
  * We need landing pages for Samples (specimens?) like we have a landing page per project
  * We need some process to either pre-generate sample metadata TSVs (I suggest using the exact same format as our file oriented metadata dump files, just filtered for a given sample/specimen).
    * We need to choose between static files or an index in ES
    * We need either to generate on a schedule or to generate in response to events from the Data Store. 
    * Maintain the metadata TSV/JSON generation script codebasePlanning to have azul service update 
 the project metadata dump when there's an update to a bundle.
    * TJ mentioned making it clear if this is a service that others can build on or if this is just for metadata download for the portal.  I think for Q2 the focus is the latter and we don't suggest that people build on top of the metadata TSV as a service for other apps/portals/services
* Other:
    * Adrienne will provide feedback on this from beta 2
    * Brian mentioned need to link metadata.tsv to manifests from the Data Browser, a user will need to be able to link both. The manifest file contains links to the metadata files downloaded by the CLI.

**Note**: I confirmed this proposal above with @kozbo and @theathorn on 20190417 and they have/will link appropriate Epics from across their teams (and ask other teams to do the same) to these theme epic via ZenHub to track the work to be done in Q2.

**For more information see**: https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M

**Comment by theathorn** [comment]
From https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M Label A deliverable: "Establish a first iteration of metadata accessible for download and demonstrate downloading that metadata through the data browser for a project and additionally for a sample".

**Comment by tburdett** [comment]
@theathorn I'd like to make sure the work that the Ingestion Service needs to do is reflected in this epic, but I don't have enough information about the scope of what you're planning to do here. I appreciate you're likely waiting for results from beta 2 but if you're thinking of something else can you add some information about what?

If you need the Ingestion Service to modify the way it creates bundles or modify the way links between metadata documents within a bundle are captured, can you let Norman (or me or Laura whilst he's on holiday) know ASAP?

**Comment by theathorn** [comment]
@tburdett The planned work for this is detailed in the attached Epic "MVP for improved metadata access for the end user". The data browser will provide a tsv-per-project (and perhaps a json-per-project) for direct download from the Project Details page. I'm not aware of any need changes for the Ingestion Service.
I note that this Epic is also requesting a "metadata download per sample" which is not part of our current plan and sounds like a lot of additional work. This needs further discussion with @hannes-ucsc and @NoopDog.

**Comment by tburdett** [comment]
OK, based on the linked epic and the doc, I'd agree the Ingestion Service appears to not be impacted by these changes. I'll change the status of the work for ingest in our roadmap doc to "informed" - keep us looped in!

I have a suspicion that we could change the granularity or the profile of the way data is organised in bundles to make life simpler for the data browser. However, this is very different to the work you're currently proposing, so I'm happy to table that conversation for now.

**Comment by lauraclarke** [comment]
So a point of information and a question.

@simonjupp told me he has handed the TSV script to @hannes-ucsc and @GPelayo. If you want to hand it back, happy to have that discussion. I note the unassigned bit at the bottom is related to defining ownership for that codebase.

The question is what do you mean by stable metadata? We aren't intending to make any major style changes again anytime soon, the only thing which might trigger that would be significant feedback from portal developers that the current style was challenging and the cost/value discussion demonstrated changing the style again was worth it

As far as new fields or updating fields due to scientific drivers, that won't go away. I hope that editing existing fields will start to reduce for scRNA-seq but I imagine imaging data might see more churn because it hasn't been used much yet so it is much more stable. 

I think a strong requirement for the codebase which does this metadata translation will be being agnostic to the schema and working on introspection rather than hard coding. @simonjupp will have plenty of design hints for whoever takes on ownership of the codebase.

That being said the metadata team has started working on structures to understand field name changes programmatically and we imagine that the new DCC group will be drawn into this too as upgrading data to new schemas seems like a likely release task. Happy to get requirements for schema migrations in this context.

**Comment by theathorn** [comment]
**MVP for Q2**
  - Manual generation of per-project metadata tsv files.
  - Provide documentation for user to grep the per-project metadata.tsv file for the required sample.

**Improvements for Q3**
  - Automatic generation of per-project metadata tsv files (databiosphere/azul#902).
  - Download of metadata tsv file per sample (humancellatlas/data-browser#559).

**Comment by adriennes** [comment]
Another deliverable to add: Incorporate feedback from beta 2 from UX team to make sure this metadata file is digestible and discoverable

**Comment by theathorn** [comment]
@hannes-ucsc Orange team has been asigned ownership of the metadata tsv script and how to maintain it in the face of future metadata changes.

**Comment by theathorn** [comment]
Waiting for @hannes-ucsc to review and promote remaining 2 Azul changes to prod.

**Comment by brianraymor** [comment]
During the July 18 Refinement meeting, there was a question about whether there was _high confidence_ that this would complete by Milestone 1 based on pending issues. @theathorn to review and confirm.

**Comment by theathorn** [comment]
3 remaining issues: 2 in Review and 1 blocked waiting for the others to be deployed.
Now expect this to complete early in M3.

**Comment by theathorn** [comment]
2 issues remaining (In Progress). Targeting release to prod next week.
