### ISSUE TITLE
Data consumers can get analysis results for a single project

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp#357]
**Overview**: Data consumers can get analysis results for a single project.

**User Story**: As a researcher with a pipette/keyboard, I want to filter the analysis results from the DCP for a specific project so that I can get a feel for whether the DCP has data that I’m interested in

**Delivery at the end of Q2**: 1) Links on project pages to the matrix service for this project.  Users can see a summary of the data available on a project page and click a link (or links) to download a matrix/matrices for gene expression data for a given project. 2) Alternatively, a user can use the data browser to narrow down to a single project and then use the matrix service option in the browser to download that project’s worth of gene expression data without visiting the project page.

~**Evaluation Plan - how this will be evaluated at the end of the quarter**: 1) There is a tutorial (on or pointed to from our “[Guides](https://dev.data.humancellatlas.org/guides)” portal section) that a researcher can follow that will show them how to 1) navigate to and understand project pages including what the matrix download link/links do and 2) search and download matrix data using the data browser.~

~** Needs from Responsible Groups**:~
~* TJ - Query Service~
 ~* Coordination with Matrix Service to provide info for project-level lookup~
  ~* Help write/validate tutorials~
~* Ambrose - Matrix Service~
  ~* Support the creation of matrices using a project query (assuming this is done leveraging the query service)~
  ~* Help write/validate tutorials~
~* Brian - Data Browser/Data Store~
 ~* For deliverable 1, links on the project page to a matrix for that project ~
    ~* These links will either be dynamic (if the matrix service support lookup by project ID, see above) or will be generated on a schedule and stored per project, ready for download~
  ~* For deliverable 2, this was already described in DCP #337~
 ~ * We need to write the tutorials with the partners above~

~**Note**: I confirmed this proposal above with @kozbo and @theathorn on 20190417 and they have/will link appropriate Epics from across their teams (and ask other teams to do the same) to these theme epic via ZenHub to track the work to be done in Q2.~

**For more information see**: https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M

**Comment by theathorn** [comment]
From https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M Label F: "Deliverable: Links on project pages to the matrix service for this project".

**Comment by brianraymor** [comment]
**20190425 Product Owner review** - Agreed to strike solution in favor of a UX Spike.

**Comment by theathorn** [comment]
Agreed with @mckinsel to have a pre-generated per-project matrix file which can be downloaded directly from the Data Browser Projects tab.

**Comment by briandoconnor** [comment]
We had a chat today with Ambrose, Adrienne, David R. Calvin, Kevin, and Trevor (sorry if I missed anyone).  Points from this meeting:

* for Q2/beta 2 we will offer 1) live integration of matrix service with the data browser and 2) regularly generated static matrix files per project
* we will do this work now for 1 and get it in place as soon as ingest is complete
* Trevor will let Adrienne know when the portal, then, is ready to go for beta2
* we'll get feedback from the beta2 users about the usability of both approaches before deciding on which method we will support going forward

**Comment by theathorn** [comment]
On track for completion in Q3 M1.
