### ISSUE TITLE
Simple updates RFC

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/dcp#366]
A [WIP](https://docs.google.com/document/d/1XeAw05RAJe20Q1XDF7eLWLGF3gCme4-8l-ZfhtDWOLg/edit). Needs extensive design in ingest and consultation with other affected components (coming soon).

t-shirt size small (one month)

**Comment by brianraymor** [comment]
@justincc - I updated to reflect the model recommended by Sam. This issue now blocks the AUDR epic. I also added the "S" label for sizing.

**Comment by lauraclarke** [comment]
@justincc Given https://github.com/HumanCellAtlas/dcp-community/pull/77 exists, is this now done?

**Comment by justincc** [comment]
I don't think so. The intention of this ticket was to cover the entire passage of the RFC.

**Comment by brianraymor** [comment]
The RFC has been approved and merged. Closing.
