### ISSUE TITLE
Engineering plan for Integration Testing Metadata Schema Changes

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/dcp#372]
## Need
We need to draw up an engineering plan to implement the integration test for metadata schema changes.

## Approach
A list of technical tasks, design amendments, and rollout plan for the the integration test described in [rfc3](https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0003-integration-testing-for-metadata-schema-changes.md).

**Comment by maniarathi** [comment]
The beginnings of a design lives here: https://docs.google.com/document/d/18C_Wbrr4Huc8yxQXSdNbzeGk0glBjkfq0MGnozwlIB8/edit

**Comment by brianraymor** [comment]
Please update the release and milestone.

**Comment by maniarathi** [comment]
Engineering plan is completed here: https://docs.google.com/presentation/d/1raYhT7YP6Dhn87B19AWeWTXZ5k5c9ynCzGKNdue3ntg/edit#slide=id.g5dcfa169f5_0_247.

Implementation has begun.

**Comment by mweiden** [comment]
@maniarathi great!
