### ISSUE TITLE
Integration testing for metadata schema changes

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/dcp#373]
2019 Q1: [rfc3](https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0003-integration-testing-for-metadata-schema-changes.md)

Update 2019 EOQ2: [Metadata Integration Testing Design](https://docs.google.com/document/d/18C_Wbrr4Huc8yxQXSdNbzeGk0glBjkfq0MGnozwlIB8/edit)

**Comment by maniarathi** [comment]
I'm closing this issue since the Epic referenced in this ticket encompasses the work done here and has been broken out into sub-tickets and sub-Epics already. i.e. this ticket is redundant since it was created before the engineering plan was formulated.
