### ISSUE TITLE
Enable "data.humancellatlas.org" as the user facing URL

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp#383]
Currently "data." redirects to "preview.data.".
Suggestion is to redirect "data." to "prod.data." when current re-ingest completes in Q2, to assist in "stable URL generation" for citable data.
Does this need OC approval?

**Comment by lauraclarke** [comment]
For clarity, when you say OC do you mean the oversight committee of the DCP or the organising committee of the HCA. Please be more specific

**Comment by theathorn** [comment]
Oversight committee.

**Comment by theathorn** [comment]
Is it true that "prod.data" will remain valid indefinitely and "data." will just redirect from "preview.data" to "prod.data"?

**Comment by theathorn** [comment]
"data.humancellatlas.org" shouls become the production site URL with "prod.data" redirecting to "data." so that users are citing the correct URLs without "prod.".

**Comment by brianraymor** [comment]
Do we also want to ensure that https://www.humancellatlas.org/data-sharing references data.humancellatlas.org if it's a primary _cave entrance_?

**Comment by theathorn** [comment]
We need assistance from Suzan at MOTHandRUST to link to the Data Portal from the current HCA site: "Please do let me know how you would like this to work when you’re ready.  We can help with any design and we can also help Sanger with implementation, if required."

**Comment by theathorn** [comment]
Linking the main HCA website to the DCP is covered by #430 and is not a GA blocker.
