### ISSUE TITLE
Get feedback from oversight committee on data citation options

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp#386]
Options:
  - Stable URL for a project (e.g. https://prod.data.humancellatlas.org/explore/projects/ff481f29-3d0b-4533-9de2-a760c61c162d)
    - Pros: easy to implement (Q2)
    - Cons: Project data/metadata can be updated after citation (citation is not immutable); project could be deleted and re-ingested rendering the citation URI invalid; doesn't use "standard" DOIs.
  - Use a 3rd part DOI assignment service such as Zenodo (https://zenodo.org/)
    - Pros: Free; provides a DOI with DCP-external storage for point-in-time project snapshot (e.g. manifest + metadata tsv files); provides versions of DOIs, allowing for updates to projects
    - Cons: relies on external service for DOI assignment; implementation may slip to Q3
  - Use Crossref DOI service previously used by EBI for project BluePrint (use existing EBI DOI prefix and account)
     - Pros: already in use by EBI; adds reference linking, cited-by, similarity check, crossmark, content registration, metadata delivery (https://www.crossref.org/membership/benefits/)
     - Cons: fees; uses EBI prefix; implementation may slip to Q3
  - the HCA to becomes an authority (Crossref member with our own HCA DOI prefix) who can assign DOIs ourselves
    - Pros: HCA can mint its own DOIs with an HCA-specific prefix
    - Cons: fees; largest implementation effort (Q3 or Q4)

**Comment by briandoconnor** [comment]
Stable URL with DOI provided via metatadata for Q2 is what was decided on in steering committee.

**Comment by theathorn** [comment]
From @briandoconnor at the Oversight Committee meeting on 5/13:
Really, given the time, we are leaning towards permanent URLs with DOIs provided via EBI system on the accession section of the project page.
Decision: yes, OK to assign DOI via ingest via BioStudies for Q2 along with stable URLs.

@lauraclarke Does this mean the DOI will be a string in the metadata "project
.biostudies_accessions" field? Will/should this be a clickable link? The stable URL will be of the form https://data.humancellatlas.org/explore/projects/<project_uuid>.

**Comment by lauraclarke** [comment]
The DOI will be an independent field which is separate from the BioStudies accession

**Comment by lauraclarke** [comment]
@morrisonnorman we need to setup a ticket for working this through with BioStudies
