### ISSUE TITLE
Create User Endpoints 

### ISSUE THREAD

**Issue by hariniczi** [HumanCellAtlas/dcp#387]
* users
* users/<userId>
* users/<userId>/<enable/disable>

**Comment by brianraymor** [comment]
@hariniczi - Why was this issue created in the top-level _dcp_ repo? Is there a more appropriate repo that it can be moved to?

**Comment by brianraymor** [comment]
Issue moved to [HumanCellAtlas/fusillade #98](https://github.com/HumanCellAtlas/fusillade/issues/98) via [**ZenHub**](https://www.zenhub.com/)
