### ISSUE TITLE
Refresh Data Model and Data Lifecycle

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/dcp#390]
## Need

DCP's Data Model and Data Lifecycle architecture and the supporting documentation is out of date. Rearticulating this documentation is critical for good alignment across project teams.

## Approach

Write an RFC that will serve as documentation of DCP's data model and lifecycle. Make design change proposals as necessary to meet DCP's scientific goals.

The Pre-RFC is being written here [Data model and life cycle pre-RFC](https://docs.google.com/document/d/1CdIJ_pBdiiQUFh8kYARRhMXvhKXGERG3bdv763tpAKI/edit).

**Comment by mweiden** [comment]
@kislyuk is looking into getting the RFC draft into the dcp-community repo this M2

**Comment by diekhans** [comment]
An informational RFC covering the versioned experimental data model has been spun out of the pre-RFC and is getting close to a PR.  Should be available week of Sept 1st, 2019.

A second RFC is planned on metadata serialization will be started after this.  

A third on bundles would be highly useful.

**Comment by mweiden** [comment]
@kislyuk @diekhans so is this the full list?

RFCs
- [ ] link versioning
- [ ] metadata serialization
- [ ] bundles*

*What, specifically, about bundles do you want to cover?

**Comment by diekhans** [comment]
s/ link versioning/experimental metadata versioning/   

I think we need a rigorous description of what role bundles fulfill in DCP.  This remains a matter of confusion, as shown by the reaction of the ticket to add a bundle tab to the browser.

**Comment by mweiden** [comment]
This work is being taken over by the Data Model Working Group. We'll reopen a separate ticket for this elsewhere.
