### ISSUE TITLE
Supporting researchers with harmonized datasets that are stored in persistent locations

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/dcp#421]
Document the basic principles that guide a robust data resource, identify where the DCP is currently fulfilling those principles, and make suggestions for where the DCP should fill in gaps (draft an informational RFC)

As a user, I want a reliable and stable data resource that allows me to find and access data that I am interested in. I want to have confidence that metadata and data have been appropriately harmonized prior to my ability to access them. I want to easily trace back the origin of data and the processes that created it for my understanding and to ensure reproducibility. This will ensure the data I use from the DCP will be interoperable with data from another resource.

9/25/19 First documents in community review

8/26/19 [Data Operations charter](https://github.com/HumanCellAtlas/dcp-community/pull/104/files)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;10/03/19 [Charter approved](https://github.com/HumanCellAtlas/dcp-community/blob/master/charters/DataOperations/charter.md)
9/17/19 [RFC Project Completion Stage](https://github.com/HumanCellAtlas/dcp-community/pull/115/files).
10/8/19 [Epic for the Project Lifecycle](https://docs.google.com/document/d/1iCOyNegmDHx6JG_7Wwtu_yj13p4tItIhgDw1_mD8wko/edit#)

**Comment by mweiden** [comment]
@jahilton @jlzamanian: @maniarathi and I are here with engineering support for you on this. Keep us in the loop as your vision solidifies and we'll help craft an engineering plan for the necessary changes to the system.

**Comment by brianraymor** [comment]
@jahilton and @jlzamanian - would you add links to *work in progress* and next steps?

**Comment by jlzamanian** [comment]
The informational RFC is being written based on the June 2019 F2F release [presentation](https://docs.google.com/presentation/d/1VnKjFqwV9uT2CTSpTszVS6UOESpB4Atr7xZcZNAKGaw/edit#slide=id.g5be8626a61_0_77) and [discussion](https://docs.google.com/document/d/1qRQZ36WYlo8WErknxnV3a95xSJPhHY1bLY3s7SUs2WA/edit).

[Data resource principles](https://docs.google.com/spreadsheets/d/1Lf51CxivFSZCL9WfKOS8VoTtn41rLyQK06siNOA-f6E/edit#gid=0)
Work in progress

We have started discussion with @maniarathi about possible engineering plans.

**Comment by brianraymor** [comment]
Is there a relationship/dependency between this research and [Ensure that projects can be cited, for example in publications](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/226) which is also in a Spike?

**Comment by jlzamanian** [comment]
@brianraymor That epic does address and seeks to fulfill an aspect of the data resource findability principle in the review.

**Comment by brianraymor** [comment]
I'm not sure that answers my question about relationship/dependency. For example, is one spike dependent on the other? Can this spike subsume the other spike? For example, are you planning to address _findability_? Right now, the scope is unclear to me.

**Comment by brianraymor** [comment]
The _Data resource principles_ are also inaccessible. Was this document created in the [DCP folder](https://drive.google.com/drive/u/0/folders/0B1PPPeXlIFfjTjJLR0toeWhPQ1k) (which should inherit the appropriate sharing permissions).

**Comment by jlzamanian** [comment]
This epic is the top level multi-quarter epic for the theme "Supporting researchers with harmonized datasets that are store in persistent.

**Comment by jlzamanian** [comment]
[Data Operations charter](https://github.com/HumanCellAtlas/dcp-community/pull/104/files) is in community review.

The first of several RFCs is in community review: [RFC Project Completion Stage](https://github.com/HumanCellAtlas/dcp-community/pull/115/files).

**Comment by jlzamanian** [comment]
The next proposal towards this theme is the [Epic for the Project Life Cycle](https://docs.google.com/document/d/1iCOyNegmDHx6JG_7Wwtu_yj13p4tItIhgDw1_mD8wko/edit#)

**Comment by jlzamanian** [comment]
It was decided at the 11/14/19 PM meeting that the work scoped for 2019 Q3-4 on this theme was complete and that this epic could be closed. A new epic will be opened for 2020 Q1 work towards this theme based on roadmap priorities.
