### ISSUE TITLE
Determine benchmark for deployment process

### ISSUE THREAD

**Issue by stahiri** [HumanCellAtlas/dcp#422]
In support of the Q3 objective to improve the deployment process for infrastructure, we need to reach consensus on what the benchmark for the next iteration of our deployment process should be. This is not intended to be the final version of deployment but rather an incremental improvement to the process. 

Once consensus is reached, we will assess which components have work to accomplish toward this Q3 objective + determine service level objectives that we will use to measure our improvement over the quarter.

**Comment by brianraymor** [comment]
@stahiri - Please assign a Milestone for this Spike. It must be time-boxed.

**Comment by stahiri** [comment]
Following discussion in #dcp-deployment-wg, a list of [CI/CD best practices for DCP](https://docs.google.com/document/d/1prozPLncba82WQ5FNg59kg54ZzRdgya-WwQkZsOQhMs/edit?ts=5d2dfdc7#heading=h.btrzq1j7bkz2) was generated. Feedback on this list is being gathered and will result in the goals for improved DCP deployment, at which point we will determine the iterative goals reasonable to accomplish in Q3.

**Comment by brianraymor** [comment]
@stahiri -  _CI/CD best practices for DCP_ was inaccessible on the Refinement call.

**Comment by stahiri** [comment]
Followed up with the doc owner who is updating location of this file to ensure all DCP folks can access.

**Comment by rhiananthony** [comment]
All DCP components should be able to access this doc now.

**Comment by rhiananthony** [comment]
It seems that a good baseline for deployment improvements is that every component has the following:

1) Get everyone on board with GitLab for deployments
2) Verify that deployment results are logged
3) Verify that configurations are checked in code and not manual.
4) Create Runbooks for the deployment process, which include both how to deploy each component as well as some information for debugging common issues experienced during the deployment process.
5) That software is versioned (the method of which is still open for debate)

**Comment by brianraymor** [comment]
_All DCP components should be able to access this doc now._ @rhiananthony - the document is still inaccessible.

**Comment by stahiri** [comment]
@brianraymor following up with you offline to see what trouble you're having accessing, as the doc is in the HCA folder structure

**Comment by stahiri** [comment]
The conclusion of this spike is that the following goals will be applied to the Q3 objective of [Improving deployment process for infrastructure](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/420) (which will be re-scoped with this information):

(1) All deployments be done on GitLab. This will capture all deployment results in one tool. By virtue of having all deployments done on GitLab, we will have logged deployment results.
2) All configuration changes are in gitlab and no configuration is being done manually
3) We have runbooks describing the deployment process to anyone who would try to deploy any component.
4) (stretch) We have code coverage for our unit and integration tests so we can identify our holes in testing. This will be necessary if we want to start moving towards a more CI/CD setup. This work is a stretch goal for Q3, so may shift to Q4 work.
