### ISSUE TITLE
Define requirements for Data Citation

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp#424]
9/13/19: PR ready for community review at https://github.com/HumanCellAtlas/dcp-community/pull/103
Last call: 9/27/19

**Comment by theathorn** [comment]
See functional spec: https://docs.google.com/document/d/15U5-YbXMFaLDPLcdaqnxkYtc2uD_CyiStfPylvq1b9Y

**Comment by theathorn** [comment]
Need to update spec based on feedback from @briandoconnor. ETA 7/26.

**Comment by brianraymor** [comment]
@theathorn - if the [*work-in-progress*](https://docs.google.com/document/d/15U5-YbXMFaLDPLcdaqnxkYtc2uD_CyiStfPylvq1b9Y) will not be updated until July 26 and this is a _Pre-RFC_ (based on the comments in the *work-in-progress*),  then it sounds like this Spike will not be completed in Milestone 1 (July 28)?

**Comment by theathorn** [comment]
Next step is to convert the Google doc into a pre-RFC draft pull request.

**Comment by brianraymor** [comment]
If you're feeling lucky - https://pandoc.org/

**Comment by theathorn** [comment]
Target dates:
pre-rfc ready for internal review: 8/9/19
rfc ready for community review: 8/23/19

**Comment by theathorn** [comment]
8/23/19: Draft PR at https://github.com/HumanCellAtlas/dcp-community/pull/103

**Comment by theathorn** [comment]
Asked @lauraclarke , @morrisonnorman and @gabsie to provide feedback on draft RFC prior to review with @briandoconnor on 8/29. Estimate RFC ready for community review by 9/6.

**Comment by theathorn** [comment]
RFC approved by Tech Architecture: https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0014-data-citation-plan.md
