### ISSUE TITLE
Redirect "prod" to final production URL

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp#429]
Regarding our "GA" transition to "data.humancellatlas.org" for production, Parth agreed to assist with DNS redirecting "prod.data." to just "data."

**Comment by parthshahva** [comment]
When do you want this done @theathorn ?

**Comment by theathorn** [comment]
@jahilton is coordinating this effort. Don't do anything until you get the go ahead..

**Comment by jahilton** [comment]
GA now has the Green Light. This ticket will follow https://github.com/HumanCellAtlas/data-browser/issues/621

**Comment by theathorn** [comment]
Tested various scenarios and all appears to be working.
