### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#43]
A way to 1) test that the DCP is easy for users to use and 2) provide instructions on how to use the DCP is to create use case vignettes. The vignettes live in https://github.com/HumanCellAtlas/data-consumer-vignettes  
Status can be found [here](https://github.com/HumanCellAtlas/data-consumer-vignettes/blob/master/README.md): 
✅	Install the HCA CLI
🔶	Log in to the DSS
🌕	Stream FASTQs and Calculate k-mers with SPARK
🌕	Download any BAM file
🔶	Download FASTQs associated with a known sample ID
🔶	Download SmartSeq2 expression matrix as an input to scanpy
🌕	Find out how many liver (whatever) cells are available
🌕	Download all bundles for T-cells sequenced with 10x
🔶	Compare QC metrics between one experiment and another
⚪️	Check gene expression of key markers for immune cells
⚪️	Compare averaged gene expression of neurons to bulk controls
⚪️	Find most variable genes in monocytes across experiments
⚪️	Identify most differentially expressed genes between t-cells and monocytes
⚪️	Discover novel liver cell types by cross-referencing HCA single cells with known datasets

**Comment by kozbo** [comment]
Note that all Vignettes will have to be updated to use the production deployment once the production deployment has analysis data. Note that these vignettes will have to be updated regularly as we move forward with our metadata and system improvements.

**Comment by theathorn** [comment]
Need a plan...

**Comment by brianraymor** [comment]
@tjchen and @jodihir - can this be closed or repurposed in favor of a unified **Content** epic?

**Comment by jodihir** [comment]
Yes, I think that works.  We are going to discuss the vignettes with TJ at our content team meeting tomorrow.

**Comment by brianraymor** [comment]
Closing in favor of a well-defined Content epic.
