### ISSUE TITLE
DCP Support for 10X and SS2 Mouse data

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#44]
**November 19 Update** The remaining Data Browser tickets will complete in Q4M3. 4/5 tickets are merged but there was no promotion to prod this week. The remaining ticket is more-complex-than-expected work to accommodate multiple species in the UI download, but in now In Review/QA.

**October 10 Update** The Matrix service supports mouse matrices in production now. Work to turn on subscriptions for Optimus and SS2 and to process existing data is underway.

**October 4 Update** - The mouse reference for both Optimus and Smartseq2 have been approved as a Standard pipeline.

**September 25 Update - change in Release and Milestone**:  This objective will slip into Q4M1. The matrix service child issue was slightly underestimated and will complete one week late (Q4M1W1). The original objective included no dependencies on the data browser, but based on recent [AWG Guidance](https://docs.google.com/document/d/1YcSg2DhePi1Ozb0ty7_pGdAPiPeN9B6WaDhuN0PiYRU/edit#heading=h.qf4cth7gazsu), both the matrix service and the data browser must support new requirements:

* All queries are human by default.
* Separate matrices are returned per species (rather than being aggregated).

Additional child issues have been added for the data browser which are scheduled for completion by Q4M1.

---

Why? We have multiple beta datasets that are mouse 10X and SS2.

## Q3
**Objective:** Users can submit and access processed model species (mouse) data for 10X and SS2.
**Demo:** Showing SS2 analyzing Mouse data in DCP and demonstrate that mouse analyzed data shows up in portal for at least one of each type of dataset

## Q2
**Objective:** Users can submit and access processed model species (mouse) data for 10X and SS2.
**Demo:** Showing Optimus **or SS2** analyzing Mouse data in DCP and demonstrate that mouse analyzed data shows up in portal for at least one of each type of dataset

**ACs:**
- Pipeline and subscription for 10X
- Process mouse datasets

## Already done
Metadata
Browser
Portal
UX
Content

___

**Comment by theathorn** [comment]
Don't have pipelines.

**Comment by lauraclarke** [comment]
@kbergin We have discussed this internally and currently both metadata schema and the ingestion service are species agnostic. We have already successfully stored raw mouse data in the DSS so we are not expecting your work to create any new tasks for us.

There is one area where it might. If you need to capture distinct analysis metadata for your mouse pipelines compared to your human pipelines and we need to update the analysis metadata schemas. If this arises please create issues with your requirements in the metadata-schema repo and link them to this epic so we can track the progress.

**Comment by jkaneria** [comment]
Hand off GTF that pipelines choose to matrix service.

**Comment by brianraymor** [comment]
@kbergin and @jkaneria 

There was no representation at the zenhub review this morning for pipeline epics. Can the status of this epic and its dependencies in secondary analysis be updated?

**Comment by brianraymor** [comment]
@jkaneria - RE _Hand off GTF that pipelines choose to matrix service._, Ambrose has provided the reference - https://github.com/HumanCellAtlas/matrix-service/issues/279#issuecomment-497443226.

**Comment by kbergin** [comment]
Mouse work is still underway in both pipelines and pipelines infrastructure. The infrastructure team is working on being able to process more than one organism and the pipelines team is working on completing the work needed to generate a mouse reference for SmartSeq2. After that we will need to minimally validate the pipelines.

**Comment by brianraymor** [comment]
@kbergin - Can you link in the dependent issues for _mouse work is still underway ..._? There doesn't seem to be much detail in - https://github.com/humancellatlas/secondary-analysis/issues/320.

**Comment by kbergin** [comment]
@brianraymor we don't track work at that level in zenhub so I don't have tickets to represent the remaining effort. I expect it will take us until the end of the quarter to have mouse fully running in production.

**Comment by brianraymor** [comment]
HumanCellAtlas/secondary-analysis#320 - isn't even assigned to a release or a milestone. How do you track work at this level? I thought the agreement was that we were all using ZenHub as the one source of truth for the DCP engineering plan?

**Comment by kbergin** [comment]
I thought only tickets on the DCP level board were attached to releases and milestones. None of the tickets on our board are assigned in that way. We track the progress towards completing a feature by moving the feature level tickets across the board. If there’s a particular part of a feature that’s blocking another team I can add additional detail, but I believe in this case the feature itself is the blocker.

**Comment by ambrosejcarr** [comment]
I was unable to find any placeholder for SS2 Nuclei data. If/when that is prioritized, this dataset would be appropriate: [https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0209648#sec009](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0209648#sec009)

**Comment by brianraymor** [comment]
Per the August 6 Matrix Service meeting, Marcus and I agreed to keep the Matrix Service one milestone ahead of our dependency on [Support Mouse data in HCA](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/secondary-analysis/747) which slipped from Milestone 1 to Milestone 2. I've updated our issue to Milestone 3 and also updated the Milestone of this epic.

**Comment by brianraymor** [comment]
@kbergin - please do not change my informational roadmap objectives epic. It's to track which quarter this epic was originally planned for in roadmap planning.

**Comment by kbergin** [comment]
Ok - Sorry, it felt inconsistent to have a q3 milestone assigned to a q2 roadmap objective so I was trying to keep things consistent with current status.

**Comment by brianraymor** [comment]
@theathorn and team were briefed on the [AWG Guidance](https://docs.google.com/document/d/1YcSg2DhePi1Ozb0ty7_pGdAPiPeN9B6WaDhuN0PiYRU/edit#heading=h.qf4cth7gazsu) related to Mouse data at the August 19 _Data Browser meets the Matrix Service_ meeting. Data Browser is reviewing the implications such as the default (Human) and the output of one matrix per species. They will update this issue by September 9 if there are new requirements for the Data Browser that need to be incorporated.

**Comment by kbergin** [comment]
Awesome progress on this epic this Q! @brianraymor or @theathorn should this be assigned to one of you now that it is in your teams court?

**Comment by kbergin** [comment]
Messaged @theathorn offline to check in on browser support for this to enable us closing the epic. As an update, Matrix service has turned on their support in prod. Data Processing is working on turning on subscriptions, and the AWG has approved the pipelines as Standard, so we can now process all the mouse 10x v2 scrna and pe plate based ss2 data in the DCP.
