### ISSUE TITLE
AUDR: Reanalyses

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#46]
As we update our analysis pipelines or any of their inputs, we will want to reanalyze the data in the DCP that matches that pipeline. The reanalysis will be on top of the normal workload of data running through the DCP and will impact all boxes. This ticket represents the effort to enable easy, automated reanalyses, looks for the answer to open questions like: whether we will be versioning analysis bundles and whether we will be updating collections or users with the new versions of outputs. The data browser would likely want to have the analysis pipeline version as a facet.

**Comment by justincc** [comment]
Included in #416
