### ISSUE TITLE
DCP BuildBox CD

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#47]
As the operators of the DCP, we want an easy way to deploy all of the DCP services. Each service has agreed to use the buildbox created by the blue box. All of the different environments should be deployed by the buildbox, should be deployable by other groups, and eventually should be on continuous deployment off of triggers. 

- [x] Data Store
- [x] Upload
- [ ] Data Browser
- [ ] Data Portal
- [ ] Secondary analysis
- [ ] Ingestion

Post Pilot:
- [ ] Matrix

**Comment by theathorn** [comment]
Data Browser:
https://app.zenhub.com/workspace/o/databiosphere/azul/issues/232

**Comment by rhiananthony** [comment]
Closing this ticket as it appears related to this https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/77
