### ISSUE TITLE
Baseline vulnerability remediation - Critical/High findings

### ISSUE THREAD

**Issue by stahiri** [HumanCellAtlas/dcp#494]
It is imperative that we remediate existing vulnerabilities to set a baseline for our system, after which point we will require that vulnerabilities be remediated within a specific timeframe based on severity.

Each repo should remediate all Critical/High vulnerabilities that have been reported by Snyk, GitHub/Dependabot, and other sources. We request that all CRITICAL/HIGH vulnerabilities be remediated by the end of Q3.

Tips: Vulnerabilities reported by GitHub have a higher rate of relevance to the repos they're associated with, whereas Snyk has a (marginally) higher rate of false positives reported. We recommend that you address vulnerabilities reported by GitHub first, then work the findings that still remain as reported by Snyk.

Clarification on scope: New vulnerabilities identified in each component after today will require remediation. However, new vulnerabilities will be addressed in other tickets.

**Comment by stahiri** [comment]
Milestone for this epic is past-due. Outstanding tickets have been discussed with responsible parties and are scoped + on track for completion by 2019Q4M3. The epic's milestone is being updated accordingly.

**Comment by brianraymor** [comment]
@stahiri - Closing since all child issues are now closed.
