### ISSUE TITLE
Complete and publish the reliability dashboard tracking the reliability statistics made gatherable in 2019Q3

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/dcp#521]

**Comment by brianraymor** [comment]
@justincc - There is no description for this issue. Is this related to #518 or ... ?

**Comment by justincc** [comment]
I am not sure. @stahiri if your ticket actually referring to the same thing as what we discussed in the reliability wg meeting back a couple of weeks ago?

**Comment by brianraymor** [comment]
This does not meet the standards for issues on the DCP board - it has description for example and appears to be a duplicate. In addition, there was agreement on the October 3 DCP PM call to remove the related #518 epic from the Q4 roadmap objectives because _it is neither actionable nor defined._

**Comment by justincc** [comment]
This is an essential, and indeed the only dcp-wide component of #519, the reliability 2019Q4 epic. However, if the response is to close the ticket rather than try and improve it, so be it. This work will still need to take place anyway but just won't be tracked.
