### ISSUE TITLE
Data Releases

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#54]
Using the collections functionality, the HCA OC would like to be able to cut 'releases' of the HCA DCP on an occasional basis. These releases could require extra analysis on the data in the DCP, would ignore tombstoned data and old versions of bundles, and would create a citable manifest for referencing the entire dataset in the DCP.

**Comment by theathorn** [comment]
Wait for guidance from Oversight/Steering.

**Comment by mweiden** [comment]
@brianraymor @theathorn This ticket might be a little too out of date and a little too broad to be useful. Suggest:

* Close this ticket
* Wait for the forthcoming RFC from the DCC folks that will identify the gaps we have to fill to perform "data distributions"
* Make epics/tickets for each one of those gaps

Those epics and tickets will be more actionable and precise.

**Comment by jahilton** [comment]
I agree with @mweiden. The Data Operations team will start anew with release specifications.

**Comment by mweiden** [comment]
@jahilton OK great. I'm going to ask for forgiveness rather than permission...
