### ISSUE TITLE
Transcriptomic classification of human retinal cell types with single-nuclei RNA-seq. (9c20a245-f2c0-43ae-82c9-2232ec6b594f)

### ISSUE THREAD

**Issue by hca-data-tracker** [HumanCellAtlas/dcp#551]
<b>Project Title:</b> Transcriptomic classification of human retinal cell types with single-nuclei RNA-seq.<br><b>Project Short Name:</b> snRNA-seq_for_human_retina<br><b>Project UUID:</b> 9c20a245-f2c0-43ae-82c9-2232ec6b594f<br><b>Wrangler/s:</b> Zinaida,A,Perova; <br><b>PI/s:</b> Margaret,,DeAngelis; Rui,,Chen; <br><b>Species:</b> ['homo sapiens']<br><b>Methods:</b> ["10x 3' v3 sequencing"]<br><b>Original Submission UUID:</b> 7d515499-b5b6-4083-95cd-6a393344865e<br><b>Tracker URL:</b> https://tracker.data.humancellatlas.org/?projectUUID=9c20a245-f2c0-43ae-82c9-2232ec6b594f<br>

**Comment by hca-data-tracker** [comment]
State of this project has changed: <br><br><b>Overall Project State:</b> COMPLETE<br><b>Primary State:</b> COMPLETE<br><b>Analysis State:</b> NOT_EXPECTED<br><b>Matrix State:</b> NOT_EXPECTED<br><br>cc @HumanCellAtlas/data-ops

**Comment by jychien** [comment]
hca-data-wrangling repo tickets:
- Rui Chen - Human retina ([#278](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/278))

**Comment by hca-data-tracker** [comment]
State of this project has changed: <br><br><b>Overall Project State:</b> INCOMPLETE<br><b>Primary State:</b> INCOMPLETE<br><b>Analysis State:</b> NOT_EXPECTED<br><b>Matrix State:</b> NOT_EXPECTED<br><br>cc @HumanCellAtlas/data-ops

**Comment by hca-data-tracker** [comment]
State of this project has changed: <br><br><b>Overall Project State:</b> COMPLETE<br><b>Primary State:</b> COMPLETE<br><b>Analysis State:</b> NOT_EXPECTED<br><b>Matrix State:</b> NOT_EXPECTED<br><br>cc @HumanCellAtlas/data-ops

**Comment by hca-data-tracker** [comment]
State of this project has changed: <br><br><b>Overall Project State:</b> INCOMPLETE<br><b>Primary State:</b> INCOMPLETE<br><b>Analysis State:</b> NOT_EXPECTED<br><b>Matrix State:</b> NOT_EXPECTED<br><br>cc @HumanCellAtlas/data-ops

**Comment by hca-data-tracker** [comment]
State of this project has changed: <br><br><b>Overall Project State:</b> COMPLETE<br><b>Primary State:</b> COMPLETE<br><b>Analysis State:</b> NOT_EXPECTED<br><b>Matrix State:</b> NOT_EXPECTED<br><br>cc @HumanCellAtlas/data-ops
