### ISSUE TITLE
Redirect the DCP preview site to the production site

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp#572]
DNS redirect preview.data.humancellatlas.org to data.humancellatlas.org

From @TimothyTickle : As long as all data in the preview site is in the DCP, I would vote to bring down the preview site and redirecting users as needed. I would do this to avoid people mistakenly citing to the site.

@briandoconnor and @lauraclarke agreed.

**Comment by parthshahva** [comment]
I will complete this next week

**Comment by theathorn** [comment]
@parthshahva ETA?

**Comment by parthshahva** [comment]
This is in progress. Will be done shortly

**Comment by theathorn** [comment]
Currently seeing this error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>preview.data.humancellatlas.org</BucketName>
<RequestId>D8A0B71880B3ECDB</RequestId>
<HostId>
garmy4x42Kxun5g+DyaykVVYNru1vq6YtMutcMDzWyv/7hEDPpurI7GARlHlHOp5XT0IdDbb3AE=
</HostId>
</Error>

**Comment by parthshahva** [comment]
Yea I've been having some problems with the s3 bucket. I'm talking to aws support. This should be completed today

**Comment by parthshahva** [comment]
I'm waiting for aws to invalidate the old cloudfront record. Unfortunately aws is slow with some deactivation and deletion procedures

**Comment by parthshahva** [comment]
@theathorn This has been completed. Please close this issue after confirming

**Comment by theathorn** [comment]
Confirmed working.
