### ISSUE TITLE
API Health Checks

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#61]
A discussion needs to happen about what should be done here. 

Notes from call discussion: In Broad, every service has a self check route, which will do sanity checks to see if all things are still up. Andrey thinks this is useful for all of our services to have.

Pingdom was something mentioned at the brainstorming sesh.

https://metrics.data.humancellatlas.org/d/v4-0_FWiz/dcp-health?orgId=1

- [x] Purple /health point returns 200
- [x] Green /health point returns 200
- [x] Upload /health point returns 200
- [x] Blue /health point returns 200
- [x] Orange /health point returns 200
- [x] Logging /health point returns 200
- [x] Monitoring Dashboard

Old trello ticket https://trello.com/c/IGNBs8t1/19-api-health-checks

**Comment by rhiananthony** [comment]
Clarification: This also includes a Route 53 metric which verifies that the endpoint is available from multiple regions and also alerts upon service being down

**Comment by theathorn** [comment]
Data Browser:
https://app.zenhub.com/workspace/o/databiosphere/azul/issues/258
https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/39

**Comment by brianraymor** [comment]
@rhiananthony and @tburdett -  Can this be closed in favor of [Provide uptime monitoring and downtime alerting of all user facing components](https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/194) and its children?

**Comment by theathorn** [comment]
From @hannes-ucsc in #248:
Health check should return 503 status if any components are down.

**Comment by theathorn** [comment]
Can this be closed in favor of #65?

**Comment by brianraymor** [comment]
See my comment in #65 - 

_What is the intersection of this Epic with #194_
--

**Comment by sampierson** [comment]
This initial project was completed.
This ticket is superseded by #282 which details additional components that need health checks.
Closing.
