### ISSUE TITLE
EU GDPR Compliance

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#62]
As part of EBI-EMBL policy we are developing draft statements for out services in order to comply with GDPR. GDPR covers any services that are collect personal information about European citizens (including services hosted outside of Europe). This means it affects us.

https://www.eugdpr.org/
Enforcement date: 25 May 2018 - at which time those organizations in non-compliance may face heavy fines. 

The list of services we offer at the moment that capture some level of personal information are:

- [x] 2) Zendesk
- [ ] 3) Preview site

These will need to have GDPR statements applied before 25th May.

---
At a minimum, services that we know of that will also likely need to comply when we go to production include:
- [X] The ingest service. 
- [ ] The Data Browser service.

NOTE - edit to remove the registry, this is no longer our responsibility but that of the scientific admin

**Comment by kbergin** [comment]
update from latest PM call - trevor and laura are in conversations to make sure this is handled for portal and ingest. Assigning them to this ticket instead.

**Comment by lauraclarke** [comment]
This is complete from an ingest perspective. More will be needed once we have a login system and a UI that the submitters interact and ingest will update our solution at that point.

**Comment by kbergin** [comment]
From @theathorn : "I have emailed the lawyers and separately emailed the UCSC ones, with zero response so far. I’m out on vacation until Tuesday and will follow up then."

**Comment by theathorn** [comment]
@kbergin The Data Portal GDPR was approved by all legal reps on 9/26/18 and has been deployed to all environments under the "Privacy" menu item. I've since updated the statement to correct a CZI address and standardize on US English throughout. So, yes, we are done!
