### ISSUE TITLE
Production deployments

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#64]
Preview release requires a production blue box by 4/2.

Pilot software release requires all components.

- [x] ingest
- [x] data store
- [x] logging
- [x] upload
- [x] Data browser
- [x] Data portal
- [x] secondary analysis

**Comment by theathorn** [comment]
Date Browser:
https://app.zenhub.com/workspace/o/databiosphere/azul/issues/85
https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/193
Data Portal:
https://app.zenhub.com/workspace/o/humancellatlas/data-portal/issues/200

**Comment by Bento007** [comment]
@kbergin what's the status of this ticket. I think it can be closed

**Comment by theathorn** [comment]
Data Browser does not have a Production deployment. Open tickets:
https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/193
https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/221

**Comment by theathorn** [comment]
Closing - we have all components running in the Prod environment.
