### ISSUE TITLE
Alerts are sent to dev/ops team for a component when it is down/unhealthy

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#65]
As a developer/operator of the DCP
when a component is down or unhealthy
I should receive an alert

Our current alert mechanism is to send messages to an appropriate Slack channel.
I believe @mweiden's status dashboard does this.  You just need to tell it where to look.

**Comment by rhiananthony** [comment]
Blocked for Secondary Analysis

**Comment by kbergin** [comment]
Not sure, but secondary analysis's relevant open tickets are linked here.

**Comment by brianraymor** [comment]
@sampierson - Should this be removed from the closed epic - https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/194?

**Comment by mweiden** [comment]
Done!
