### ISSUE TITLE
Operator Documentation (RunBooks)

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#68]
This work has shifted to Q4 as carryover MUST HAVE work.

Internal.

Runbook should detail how to deploy the component.
Runbook should detail how to roll-back a deployment.
Runbook should provide guidance on how to diagnose / resolve common problems.

Create your RunBook on allspark.dev.data.humancellatlas.org
Put a link to it in this page: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home

Examples:

https://github.com/HumanCellAtlas/ingest-central/blob/master/release-manager-playbook.md

[SOP: Releasing new Versions of DCP Software](https://docs.google.com/document/d/1HbSWuIABaavaHpCwaO0peA_uwTW5wBCdRnYoz7ZVQuQ/edit?ts=5b0d7550#heading=h.yw6cvy5vlmbu)

[Playbook template in doc form](https://docs.google.com/document/d/1EPcN1tEIwMuzRXj8JPARd-Vgnc3sXJvwQOEcVWkVaYc/edit)

**Comment by theathorn** [comment]
#68 Should perhaps be a sub-epic under this ticket and the Runbook tickets moved there.

**Comment by stahiri** [comment]
Definitely a compliance need (configuration management) but needs technical teams to develop.

**Comment by brianraymor** [comment]
@rhiananthony - This needs an unassigned Release and Milestone per the regular practice.

**Comment by brianraymor** [comment]
@rhiananthony and @stahiri - all child issues are closed. Can this epic be closed now?

**Comment by rhiananthony** [comment]
This ticket is finished
