### ISSUE TITLE
Runbooks of release and operations procedures

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#70]
# Need
After the initial prod deployment, we will need to upgrade, deploy and operate new versions of DCP software. This covers
* deploying
* making it easy enough for others to deploy
* deciding who can deploy different boxes, making sure everyone has the right perms
* recovering from common failure modes.

# Definition of Done
* Each service will post a runbook in the system's gitlab wiki. Try to use [this template](https://gist.github.com/mweiden/66787f1ac0edaf076a50abdbcdfb98ac)
* Please check it off here as well https://docs.google.com/spreadsheets/d/1YGA34Gp2TiNzPRAaOFHLZ6h1IJA5QStQQKga_6fOOpk/edit?ts=5b5fade0#gid=0
* After we move to the build boxes we will want the release management documentation updated for each service and linked in the main runbook.

- [x] Data Storage Service
- [ ] Upload
- [ ] Ingest
- [ ] Analysis
- [ ] Matrix Service
- [ ] Data Portal
- [ ] Data Browser

## Notes
From another ticket we merged in:
In general, any large version changes that introduce breaking changes need an SOP for release. The metadata team has set some standards here by coordinating closely with other boxes and giving a lot of notice before releasing new versions. Anything that could effect the prod should of course be worked out in dev, staging, int, before being deployed to production. But in general a policy on deprecation timeline, warning time, coordination steps would be helpful

**Comment by kbergin** [comment]
PMs recommend that these are most critical for the data portal and the data browser for Nov 1, as they will be the ones in active operations while the users are using the DCP. All other operations will have already happened by then. @theathorn

**Comment by sampierson** [comment]
Dup of #68
