### ISSUE TITLE
Define Escalation Paths for Incidents

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#75]
Ops Lead needed from each service:
-[] ingestion
-[] upload 
-[] data store
-[] secondary analysis
-[] orange box
-[] logging

We should also schedule an operations team meeting. Continued improvement tracking/planning

**Comment by sampierson** [comment]
@kozbo said: @Sam Pierson Jodi, Matt, Mallory, Rhian and I have been working on a doc to describe the escalation path, which we are turning into an RFC. We are hoping to submit it by the end of the week.

**Comment by kozbo** [comment]
Document in progress is here: https://docs.google.com/document/d/1urMBYYi0_I8LNd8BwtuCBZguN7t_OdayHw7k2wQ_NrA/edit?usp=sharing

**Comment by stahiri** [comment]
@kozbo can you confirm whether or not this work is complete? In the meantime, I'm removing the tag for GA release as this will need to be updated.

**Comment by kozbo** [comment]
Correct, this is meant for user issues not security incidents. The RFC is stuck waiting for oversight to decide how to structure the funding. Groups will not sign off on thew RFC unless it will be funded.

Here is the RFC: https://github.com/HumanCellAtlas/dcp-community/pull/72

**Comment by kozbo** [comment]
Assuming that this ticket is only about tracking user issues and not security incidents, I am closing this ticket. As noted above the work for how we will track user issues is being tracked in a separate repo.
