### ISSUE TITLE
Testing metadata flags

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#82]
This came up after unexpected scale tests were performed in the DCP.
Conversation started here: https://humancellatlas.slack.com/archives/C75G0R97E/p1523287041000736

I think we need four metadata entries that separately indicate “this is test data” (not real data), “don’t store this data” (Ingest would drop this when asked to store in data store), “don’t index this data” (blue box would store it but not index it), and “don’t analyze this data” (store it, index it, but green box will ignore it). @mallory.freeberg @dwelter can you propose a place in the metadata where we might store these?

“don’t store” would typically be for Ingest use only, to allow them them to exercise the machinery of metadata/data processing and storage without actually needing a blue box.
“don’t index” would allow the testing of the Purple -> Blue interface, without causing anything to be indexed that might trigger a search subscription.
“don’t analyze” would allow testing of Blue indexing too, without triggering any pipelines in subscribers who are aware of that flag.

**Comment by rhiananthony** [comment]
Sam - July 11, 2018 - 11:08AM
Had a meeting with Simon and am going to re-write the Metadata Flags RFC


Kylee - Apr 9, 2018 - 4:40PM
https://github.com/HumanCellAtlas/RFCs/blob/335ab9adb900ccc0ef938b5aa4afddd90e64e916/0000-integration-metadata-flags.md
HumanCellAtlas/RFCs: Pull Request 1

**Comment by sampierson** [comment]
This idea, while a good one, never got any traction.  Closing.
