### ISSUE TITLE
New Bundle Structure

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp#85]
*Rationale/Use Case:*
We are changing our bundle structure to a more graph based format. Makes export of bundles to the data store less complex, reduces redundancy of files written to data store. Reduces overhead for updates.

*Value:*
Value is to DCP developers, not end users.

*Risks:*

[RFC Doc](https://docs.google.com/document/d/15bSO0sgo5KRWJIr6VUgZf97uL8397vUZ68AL17EC_cA/edit#)

*Progress*
Ingestion has already merged the changes into integration
Data Store has indexed new bundles
Green is working on it this sprint

*Definition of Done:*
- [ ] DCP integration test passes with new bundle structure
- [ ] Released to prod

**Comment by theathorn** [comment]
Data Browser:
https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/182
