### ISSUE TITLE
Monitoring Website Usage Stats

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#86]
Tooling to capture website usage statistics so we can understand usage funnels and drop-offs. Data Portal, Data Browser, and Ingestion

Pick a service, i.e. google analytics, make sure all the web apps embed the javascript code in their code.

**Comment by sampierson** [comment]
This is done.  Ingest is not user-facing at this time.  Browser and Portal have analytics installed.
