### ISSUE TITLE
Monitoring for Abuse

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#88]
We have a way to spot when the system is being abused. Spikes in certain numbers (submissions, pipelines running, pings to API endpoints) should raise flags if they go over a threshold. 

-[] Identify what needs to be monitored
-[] Identify how to monitor it
-[] Put the monitoring into a Dashboard
-[] Create notifications for thresholds
-[] Identify who should receive these notifications

**Comment by sampierson** [comment]
Closing as this covered by
#65 - Alerts are sent to dev/ops team for a component when it is down / unhealthy
and
#285 A dashboard of metrics is available for ops to monitor the aggregate activity of each component
