### ISSUE TITLE
Invisible Prod smoke test

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#89]
It would be cool to have a fake bundle that goes through the DCP prod deployment once an hour (as a suggestion) to confirm that everything is up and running smoothly. It would need to have appropriate metadata so that it is not easily found by users of the system.

**Comment by sampierson** [comment]
We can almost do this now.  We have an integration test that can run in prod, and it cleans up after itself (tombstomes bundles).
