### ISSUE TITLE
Open Source SDLC DCP wide

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#90]
We hope to have this done but recognize we don't need it to go live. 

Current doc: https://docs.google.com/document/d/1ewEBvsOGj69oF1HY7lgOuCdxcgTNzw0ERlSHItlUjQU/edit

**Comment by sampierson** [comment]
What does this title mean?  You want to open source the DCP SDLC?  You want the DCP to use a standard open source SDLC?  You want to craft an SDLC for the DCP then open source it?  Please elaborate.

**Comment by rhiananthony** [comment]
This was a copied ticket from JIRA. I will track down the original ticket creator and get their input for this.

**Comment by rhiananthony** [comment]
I cannot find this ticket in JIRA - it appears to have been deleted. I am deleting this ticket
