### ISSUE TITLE
Detect secrets that have leaked into source code

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#91]
As a dcp developer
I want to run static analysis tools on my code
to help not ship code with gaping security holes in it.

There has been talk of running `trufflehog`, a tool to find embedded secrets in code before it is pushed.
The DevSecOps team needs to decide what static analysis tools to encourage/mandate.
Then we update the tickets in the component repos with these instructions.

Update: Real-time secrets detection will be enabled from a centralized location for all repos within the HumanCellAtlas org.

**Comment by sampierson** [comment]
Mandating measurement of test coverage is dangerously close to telling developers how to develop, which is a topic I have received great push-back on before.

Static analysis on the other hand can be a security requirement.  I'm going to change the title of this epic from "Test Coverage and Static Analysis" to "Source Code Static Analysis".

**Comment by adrazhi** [comment]
@sampierson @rhiananthony  I think given that we're talking about secrets in source code specifically it'd be better if this is renamed to something that better reflects what this actually is. Static Code analysis is more used with tools such as Codacy which analyze the code itself.

**Comment by sampierson** [comment]
Sounds good. We already have an epic for _"Ensure secrets do not leak into source code"_.  Perhaps this one should be renamed _"Detect secrets that have leaked into source code"_?

**Comment by adrazhi** [comment]
@sampierson That sounds good to me.

**Comment by sampierson** [comment]
Should we set this up as a pre-commit-hook or a step in a CI build?
I see @DailyDreaming added this to the data-store as a CI build step.
Isn't that closing the barn door after the horse is already free?
Seems like a pre-commit hook might be more effective.  @kislyuk what do you think?

**Comment by DailyDreaming** [comment]
@sampierson We're implementing both `trufflehog` and `git-secrets`.

`git-secrets` is intended for use clientside, prior to barn escape velocity.  It has the problem that it's the user's responsibility though.  @Bento007 on our side logged in and video chatted with each person on our team to verify `git-secrets` usage, but we decided that `trufflehog` is a necessary secondary precaution on the serverside "just in case" someone bypasses their `git-secrets` usage.

**Comment by sampierson** [comment]
@DailyDreaming ok thanks Lon that makes sense.  We will setup Upload the same way.

**Comment by stahiri** [comment]
For clarification, some questions about Trufflehog were posed in [325] (https://github.com/HumanCellAtlas/dcp/issues/325), which are also below for ease:

* Is the [regex list we've added] (https://github.com/HumanCellAtlas/dcplib/blob/master/components/trufflehog_regex_patterns.json) sufficient? **Yes**
* Which repos should trufflehog checking be added to? (See the [data-store implementation] (https://github.com/HumanCellAtlas/data-store/pull/1985) ) **Ideally all repos, have a job that does weekly scans**
* Trufflehog currently only checks regex. High entropy string matching seems to pick up a lot of noise (pages and pages in the data-store). Is the high entropy string matching something we should put effort into leveraging? **High entropy string matching does pick up a lot of noise so until we think of a better way or solution to handle this you can focus on regex support for now**

**Comment by DailyDreaming** [comment]
@stahiri I think that succinctly captures all points I had.

**Comment by stahiri** [comment]
Updating this to Q3 release since we're actively working within the DevSecOps team to implement Trufflehog from a central location as a check on each PR

**Comment by brianraymor** [comment]
Please set a milestone if possible.
