### ISSUE TITLE
User Feedback Process

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#95]
So far, Canny has been piloted as an option for user feedback tracking, curation, and dissemination. An SOP of usage is needed, but this is out of scope for this team. This has been added to the PM team's AI's to make sure this happens with whomever should be doing it.

**Comment by adriennes** [comment]
We've decided to use the dcp-feedback repo for collecting issues/ feature requests that aren't immediately translated into bugs.  Will revisit after the closed beta to make sure this is functioning, but decision was to not introduce yet another tool.
