### ISSUE TITLE
SLOs

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/dcp#98]
Setting SLOs for the DCP boxes.

We recognize that these need to be nailed down, but arguably could go to production without them. However, we'd want them very soon after, and they would inform a lot of our other SOPs for operations. If there is time, they should be done. 

ArrayExpress has some for user facing SLOs.

**Comment by rhiananthony** [comment]
Matt - May 8, 2018 - 11:49AM
Draft here https://docs.google.com/document/d/1lhi0A7Bi6jTSAECrGuN4s4V3clkZXNtuNGsyTxvlzYM/edit#heading=h.a9hm36ahuj8

Kylee - Mar 7, 2018 - 12:48PM
https://docs.google.com/document/d/1lhi0A7Bi6jTSAECrGuN4s4V3clkZXNtuNGsyTxvlzYM/edit

**Comment by mweiden** [comment]
This work has been completed, framed with scale tests. See [this doc](https://docs.google.com/document/d/1OrKjfDR97fTugXprgkundI8i4k8SNOizcoz5fRTb8PU/edit#)
